#!/usr/bin/env python3
"""Generate data/test-01.json with exactly 60 MCQs."""

import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "data" / "test-01.json"

# (category, topic, difficulty, type, question, options, answer, explanation, code?)
QUESTIONS = [
    # === CORE JAVA (10): 3 easy, 4 medium, 3 hard ===
    ("core-java", "Core Java", "easy", "theory",
     "Which keyword declares a class that cannot be subclassed?",
     ["extends", "implements", "final", "static"], 2,
     "The final keyword on a class prevents inheritance. extends/implements relate to inheritance; static is unrelated."),
    ("core-java", "Core Java", "easy", "theory",
     "What is the default value of an uninitialized int field in a Java object?",
     ["0", "null", "undefined", "-1"], 0,
     "Primitive int fields default to 0. null applies only to reference types."),
    ("core-java", "Core Java", "easy", "code",
     "What does this code print?",
     ["5", "6", "Compile error", "Runtime error"], 0,
     "Post-increment (i++) returns the old value (5) then increments i.",
     "public class Demo {\n  public static void main(String[] args) {\n    int i = 5;\n    System.out.println(i++);\n  }\n}"),
    ("core-java", "Core Java", "medium", "theory",
     "Which statement about Java interfaces (Java 8+) is correct?",
     ["Interfaces can have private instance methods callable from default methods",
      "All interface methods must be public abstract",
      "Interfaces cannot extend other interfaces",
      "default methods must be static"], 0,
     "Java 8+ allows default and static methods; private instance methods were added in Java 9 for code reuse inside interfaces."),
    ("core-java", "Core Java", "medium", "code",
     "What is printed?",
     ["true", "false", "Compile error", "RuntimeException"], 1,
     "String literals are interned; == compares references. new String(\"hi\") creates a distinct heap object.",
     "public class Eq {\n  public static void main(String[] args) {\n    String a = \"hi\";\n    String b = new String(\"hi\");\n    System.out.println(a == b);\n  }\n}"),
    ("core-java", "Core Java", "medium", "theory",
     "Which collection guarantees insertion order and allows duplicates?",
     ["HashSet", "TreeSet", "ArrayList", "PriorityQueue"], 2,
     "ArrayList maintains insertion order. HashSet/TreeSet are Set implementations; PriorityQueue orders by priority, not insertion."),
    ("core-java", "Core Java", "medium", "practical",
     "A method declares `throws IOException` but the caller does not handle or declare it. What happens?",
     ["Compiles; IOException is unchecked", "Compile-time error", "Runs but logs a warning", "JVM wraps it in RuntimeException automatically"], 1,
     "IOException is a checked exception; callers must catch it or declare throws. Unchecked exceptions need no handling."),
    ("core-java", "Core Java", "hard", "code",
     "What is the output?",
     ["[A, B]", "[A]", "UnsupportedOperationException at runtime", "Compile error"], 2,
     "Arrays.asList returns a fixed-size list backed by the array; structural modifications throw UnsupportedOperationException.",
     "import java.util.*;\npublic class L {\n  public static void main(String[] args) {\n    List<String> list = Arrays.asList(\"A\", \"B\");\n    list.add(\"C\");\n    System.out.println(list);\n  }\n}"),
    ("core-java", "Core Java", "hard", "theory",
     "In polymorphism, which binding applies when invoking an overridden instance method through a superclass reference?",
     ["Static binding at compile time based on reference type",
      "Dynamic binding at runtime based on actual object type",
      "Binding is undefined for overridden methods",
      "Only private methods use dynamic binding"], 1,
     "Instance method calls are virtually dispatched: the JVM selects the implementation from the runtime object's class."),
    ("core-java", "Core Java", "hard", "theory",
     "Which is true about try-with-resources?",
     ["Resources must implement AutoCloseable",
      "catch blocks are mandatory",
      "finally always runs before close()",
      "It cannot be used with multiple resources"], 0,
     "try-with-resources requires AutoCloseable (or Closeable). Multiple resources are supported; close runs in reverse order after try/catch/finally."),

    # === DBMS (10): 4 easy, 3 medium, 3 hard ===
    ("dbms", "DBMS", "easy", "theory",
     "Which SQL clause filters rows before grouping?",
     ["HAVING", "WHERE", "ORDER BY", "GROUP BY"], 1,
     "WHERE filters rows before aggregation. HAVING filters groups after GROUP BY."),
    ("dbms", "DBMS", "easy", "theory",
     "A primary key column must be:",
     ["Nullable and non-unique", "Unique and not null", "A foreign key", "Always an integer"], 1,
     "Primary keys uniquely identify rows and cannot be NULL."),
    ("dbms", "DBMS", "easy", "theory",
     "Which normal form removes partial dependency on a composite key?",
     ["1NF", "2NF", "3NF", "BCNF"], 1,
     "Second normal form (2NF) eliminates partial dependencies of non-key attributes on part of a composite primary key."),
    ("dbms", "DBMS", "easy", "theory",
     "What does ACID stand for in transactions?",
     ["Atomicity, Consistency, Isolation, Durability",
      "Availability, Consistency, Integrity, Distribution",
      "Atomicity, Concurrency, Indexing, Durability",
      "Authentication, Consistency, Isolation, Data"], 0,
     "ACID: Atomicity (all-or-nothing), Consistency (valid state), Isolation (concurrent safety), Durability (committed survives failure)."),
    ("dbms", "DBMS", "medium", "code",
     "How many rows does this INNER JOIN return if Orders has 3 rows (all with valid customer_id) and Customers has 2 matching customers?",
     ["2", "3", "6", "0"], 1,
     "INNER JOIN returns matching combinations; each order row joins its customer once, so 3 rows.",
     "SELECT o.id FROM Orders o\nINNER JOIN Customers c ON o.customer_id = c.id;"),
    ("dbms", "DBMS", "medium", "theory",
     "Which isolation level prevents dirty reads but allows non-repeatable reads?",
     ["READ UNCOMMITTED", "READ COMMITTED", "REPEATABLE READ", "SERIALIZABLE"], 1,
     "READ COMMITTED blocks dirty reads. Non-repeatable reads can still occur when another transaction updates a row you re-read."),
    ("dbms", "DBMS", "medium", "practical",
     "You need to list employees who have no department assignment. Which pattern is correct?",
     ["INNER JOIN departments", "LEFT JOIN departments WHERE departments.id IS NULL",
      "CROSS JOIN departments", "WHERE departments.id = 0"], 1,
     "LEFT JOIN keeps all employees; filtering WHERE dept side IS NULL finds rows with no match (no department)."),
    ("dbms", "DBMS", "hard", "theory",
     "A table is in 3NF but has a determinant that is not a superkey (non-trivial FD X→Y where X is not a superkey). What applies?",
     ["Still BCNF", "Violates BCNF; may need decomposition", "Violates 1NF only", "No normalization issue"], 1,
     "BCNF requires every determinant in a functional dependency to be a superkey. 3NF can still violate BCNF in edge cases."),
    ("dbms", "DBMS", "hard", "theory",
     "Two transactions both read balance=100, add 50, write 150 without proper isolation. What anomaly occurred?",
     ["Dirty read", "Lost update", "Phantom read only", "Deadlock only"], 1,
     "Lost update: concurrent reads and writes overwrite each other; one increment is lost without locking or serializable isolation."),
    ("dbms", "DBMS", "hard", "code",
     "Which query returns the second-highest salary using standard SQL (no LIMIT tricks on empty sets)?",
     ["SELECT MAX(salary) FROM emp WHERE salary < (SELECT MAX(salary) FROM emp)",
      "SELECT salary FROM emp ORDER BY salary LIMIT 1 OFFSET 1",
      "SELECT TOP 2 salary FROM emp",
      "SELECT MIN(salary) FROM emp"], 0,
     "Nested MAX finds the maximum below the overall max, i.e. second highest. LIMIT/OFFSET works but option A is portable subquery style.",
     "-- employees(salary)\n-- 100, 200, 300 => returns 200"),

    # === BACKEND (10): 3 easy, 5 medium, 2 hard ===
    ("backend", "Backend", "easy", "theory",
     "In Spring Boot, which annotation marks the main application entry class?",
     ["@Controller", "@SpringBootApplication", "@Entity", "@Autowired"], 1,
     "@SpringBootApplication combines @Configuration, @EnableAutoConfiguration, and @ComponentScan."),
    ("backend", "Backend", "easy", "theory",
     "Which HTTP method is idempotent and typically used to retrieve a resource?",
     ["POST", "GET", "PATCH", "CONNECT"], 1,
     "GET is safe and idempotent for reads. POST creates; PATCH may be non-idempotent depending on semantics."),
    ("backend", "Backend", "easy", "theory",
     "What does ORM stand for in Hibernate context?",
     ["Object-Relational Mapping", "Open Resource Model", "Operational Risk Management", "Ordered Record Merge"], 0,
     "Hibernate maps Java objects to relational tables and handles persistence operations."),
    ("backend", "Backend", "medium", "theory",
     "Which Spring annotation injects dependencies by type when multiple beans exist and one is marked primary?",
     ["@Resource only", "@Autowired with @Qualifier or @Primary", "@Transactional", "@RequestMapping"], 1,
     "@Autowired resolves by type; @Qualifier disambiguates. @Primary designates a default bean when multiple candidates exist."),
    ("backend", "Backend", "medium", "theory",
     "In REST, what status code should represent successful resource creation?",
     ["200 OK", "201 Created", "204 No Content", "302 Found"], 1,
     "201 Created indicates a new resource was created, often with a Location header. 200 is generic success; 204 has no body."),
    ("backend", "Backend", "medium", "theory",
     "Which Hibernate fetch strategy loads associated collection when the parent entity is loaded?",
     ["Lazy (default for collections)", "Eager always for all associations",
      "Fetch is not configurable", "Only @Transactional controls fetch"], 0,
     "Collections default to LAZY; they load when accessed inside an active session. EAGER loads immediately with parent."),
    ("backend", "Backend", "medium", "practical",
     "A @RestController method returns an object. Which component serializes it to JSON by default in Spring Boot?",
     ["HttpMessageConverter (Jackson)", "JSP view resolver", "Hibernate Session", "FilterChain only"], 0,
     "MappingJackson2HttpMessageConverter (Jackson) serializes @ResponseBody return values to JSON when Accept/content-type is JSON."),
    ("backend", "Backend", "medium", "theory",
     "Spring Security filter chain runs before which component handles @RequestMapping?",
     ["DispatcherServlet", "EntityManager", "DataSource", "Tomcat APR"], 0,
     "Security filters execute in the servlet container chain before requests reach DispatcherServlet and controller methods."),
    ("backend", "Backend", "hard", "theory",
     "Why is `@Transactional` on a private method often ineffective in Spring?",
     ["Spring uses JDK proxy/CGLIB on the bean; self-invocation bypasses the proxy",
      "Private methods are always transactional",
      "Hibernate ignores private methods",
      "Transactions require public static methods only"], 0,
     "Transactional advice applies via proxy. Calling a private @Transactional method from within the same class bypasses the proxy."),
    ("backend", "Backend", "hard", "theory",
     "JWT access tokens stored only in localStorage are criticized because:",
     ["They expire too quickly", "XSS can steal tokens from browser storage",
      "They cannot contain claims", "Servers cannot validate them"], 1,
     "localStorage is accessible to JavaScript; XSS attacks can exfiltrate tokens. HttpOnly cookies mitigate XSS token theft."),

    # === DOCKER (10): 3 easy, 4 medium, 3 hard ===
    ("docker", "Docker", "easy", "theory",
     "What is a Docker image?",
     ["A running process", "A read-only template for containers", "A volume mount", "A Git branch"], 1,
     "Images are immutable templates; containers are runnable instances of images."),
    ("docker", "Docker", "easy", "theory",
     "Which command lists running containers?",
     ["docker images", "docker ps", "docker build", "docker pull"], 1,
     "docker ps shows running containers; docker images lists images."),
    ("docker", "Docker", "easy", "theory",
     "In Git, which command creates a new branch and switches to it?",
     ["git merge", "git checkout -b feature", "git stash pop", "git revert HEAD"], 1,
     "git checkout -b (or git switch -c) creates and checks out a branch. merge combines histories."),
    ("docker", "Docker", "medium", "theory",
     "What is the purpose of a Docker volume?",
     ["Store images on disk", "Persist data outside the container writable layer",
      "Replace Dockerfile", "Encrypt container traffic"], 1,
     "Volumes persist data independently of container lifecycle, surviving container removal unless explicitly deleted."),
    ("docker", "Docker", "medium", "practical",
     "Which Dockerfile instruction sets the default command when a container starts?",
     ["FROM", "CMD or ENTRYPOINT", "EXPOSE only", "MAINTAINER"], 1,
     "CMD/ENTRYPOINT define what runs at container start. FROM sets base image; EXPOSE documents ports."),
    ("docker", "Docker", "medium", "theory",
     "What does `docker compose up -d` do?",
     ["Deletes all volumes", "Starts services defined in compose file in detached mode",
      "Builds images without starting", "Pushes to registry"], 1,
     "-d runs containers in the background. compose up creates/starts services per docker-compose.yml."),
    ("docker", "Docker", "medium", "theory",
     "Which Git command safely updates your feature branch with latest main without a merge commit?",
     ["git push --force", "git rebase main", "git reset --hard origin/main", "git clean -fd"], 1,
     "Rebase replays commits on top of main for linear history. force push and hard reset are destructive if misused."),
    ("docker", "Docker", "hard", "theory",
     "Multi-stage Docker builds primarily help by:",
     ["Running multiple containers in one process",
      "Separating build dependencies from a smaller runtime image",
      "Eliminating the need for .dockerignore",
      "Making containers privileged"], 1,
     "Build stages compile artifacts in one image and copy only outputs to a slim runtime stage, reducing attack surface and size."),
    ("docker", "Docker", "hard", "practical",
     "A container cannot reach a service on the host machine at localhost:5432. On Linux, a common fix is:",
     ["Use host.docker.internal or host network mode where supported",
      "Change PostgreSQL to port 80 only",
      "Remove bridge networking entirely always",
      "Set CMD to localhost"], 0,
     "Inside a container, localhost is the container itself. host.docker.internal (or --network host on Linux) reaches the host."),
    ("docker", "Docker", "hard", "theory",
     "Which statement about image layers is correct?",
     ["Each Dockerfile instruction can create a layer; shared layers are cached and reused",
      "Layers are writable at runtime in running containers",
      "docker pull always rebuilds from scratch ignoring cache",
      "Images cannot share layers between repositories"], 0,
     "Union filesystem layers stack read-only; build cache reuses unchanged layers. Container writable layer is separate."),

    # === ANGULAR (10): 3 easy, 5 medium, 2 hard ===
    ("angular", "Angular", "easy", "theory",
     "Which decorator marks a class as an Angular component?",
     ["@Injectable", "@Component", "@NgModule", "@Pipe"], 1,
     "@Component defines template, selector, and styles. @NgModule groups declarations."),
    ("angular", "Angular", "easy", "theory",
     "Which module is required for template-driven forms (ngModel)?",
     ["FormsModule", "HttpClientModule", "RouterModule only", "BrowserModule only"], 0,
     "FormsModule provides NgModel and template-driven form directives. Reactive forms use ReactiveFormsModule."),
    ("angular", "Angular", "easy", "theory",
     "What does the Angular router use to navigate between views?",
     ["URL paths and route configuration", "Only localStorage keys", "SQL queries", "Docker compose"], 0,
     "RouterModule maps paths to components via routes array and routerLink/router.navigate."),
    ("angular", "Angular", "medium", "theory",
     "In reactive forms, which class represents a single control with validators?",
     ["FormGroup", "FormControl", "FormArray only", "NgForm"], 1,
     "FormControl tracks value and validation for one field. FormGroup aggregates controls."),
    ("angular", "Angular", "medium", "code",
     "What binding syntax passes a number (not string) to a child @Input()?",
     ["value=\"42\"", "[value]=\"42\"", "(value)=\"42\"", "*value=\"42\""], 1,
     "Property binding [value]=\"42\" passes number 42. value=\"42\" passes string \"42\"."),
    ("angular", "Angular", "medium", "theory",
     "HttpClient GET returns what type by default?",
     ["Promise<string>", "Observable of the response body", "XMLHttpRequest sync", "BehaviorSubject"], 1,
     "HttpClient methods return Observables; subscribe or async pipe consumes them."),
    ("angular", "Angular", "medium", "practical",
     "A route should load a module lazily. Which configuration is correct?",
     ["{ path: 'admin', loadChildren: () => import('./admin/admin.module').then(m => m.AdminModule) }",
      "{ path: 'admin', component: AdminModule }",
      "{ path: '**', redirectTo: 'admin' } only",
      "{ path: 'admin', providers: [AdminModule] }"], 0,
     "loadChildren with dynamic import enables lazy loading and smaller initial bundle."),
    ("angular", "Angular", "medium", "theory",
     "What is the purpose of Angular's async pipe?",
     ["Subscribes to Observables/Promises in template and unsubscribes automatically",
      "Makes HTTP synchronous", "Replaces HttpClient", "Compiles TypeScript"], 0,
     "async pipe handles subscribe/unsubscribe in templates, reducing memory leaks from forgotten subscriptions."),
    ("angular", "Angular", "hard", "theory",
     "Change detection runs and a child uses OnPush. When will the child update?",
     ["Never", "When @Input references change, events originate in child, or async pipe emits",
      "On every browser tick globally always", "Only on route change"], 1,
     "OnPush checks inputs by reference, events from component/subtree, and async pipe updates— not every parent change by default."),
    ("angular", "Angular", "hard", "theory",
     "An HTTP interceptor should add an auth header. Where is it registered?",
     ["providers: [{ provide: HTTP_INTERCEPTORS, useClass: AuthInterceptor, multi: true }]",
      "declarations array", "bootstrapModule exports", "styles.scss"], 0,
     "HTTP_INTERCEPTORS multi-provider registers interceptors in the HttpClient chain."),

    # === SOFTWARE DEVELOPMENT (10): 4 easy, 4 medium, 2 hard ===
    ("software-development", "Software Development", "easy", "theory",
     "Which SDLC phase typically produces requirements and scope documents?",
     ["Deployment only", "Planning / Requirements", "Maintenance only", "Coding only"], 1,
     "Early phases capture requirements and planning before design and implementation."),
    ("software-development", "Software Development", "easy", "theory",
     "In Agile Scrum, who owns prioritizing the product backlog?",
     ["Scrum Master", "Product Owner", "Every developer equally", "QA lead only"], 1,
     "The Product Owner maximizes value and orders backlog items. Scrum Master facilitates process."),
    ("software-development", "Software Development", "easy", "theory",
     "The 'S' in SOLID stands for:",
     ["Single Responsibility Principle", "Simple Singleton Pattern", "Secure Socket Layer", "Static Service Locator"], 0,
     "Single Responsibility: a class should have one reason to change."),
    ("software-development", "Software Development", "easy", "theory",
     "In the testing pyramid, which layer is usually the largest?",
     ["Unit tests", "E2E UI tests only", "Manual tests only", "Production monitoring"], 0,
     "Pyramid favors many fast unit tests, fewer integration tests, and few slow E2E tests."),
    ("software-development", "Software Development", "medium", "theory",
     "Open/Closed Principle means:",
     ["Open source only; closed source forbidden",
      "Open for extension, closed for modification",
      "All classes must be final",
      "APIs must use POST only"], 1,
     "Software entities should be extendable without modifying existing tested code (e.g. via interfaces/strategy)."),
    ("software-development", "Software Development", "medium", "theory",
     "Which is a REST constraint?",
     ["Stateful server session required for every call",
      "Uniform interface (e.g. resources identified by URIs)",
      "SOAP envelope mandatory", "Binary-only payloads"], 1,
     "REST emphasizes statelessness, uniform interface, cacheability, layered system, and optional code-on-demand."),
    ("software-development", "Software Development", "medium", "theory",
     "Factory Method pattern is used to:",
     ["Execute SQL faster", "Delegate object creation to subclasses or helpers",
      "Replace all interfaces", "Disable polymorphism"], 1,
     "Factory Method lets subclasses decide which concrete product to instantiate, decoupling client from concrete types."),
    ("software-development", "Software Development", "medium", "theory",
     "CI/CD pipeline 'continuous integration' primarily means:",
     ["Deploying to production once a year",
      "Frequently merging code and running automated builds/tests",
      "Only manual QA sign-off", "Disabling version control"], 1,
     "CI integrates changes often with automated build/test feedback. CD extends toward automated delivery/deployment."),
    ("software-development", "Software Development", "hard", "theory",
     "Liskov Substitution Principle implies:",
     ["Subtypes must be substitutable for base types without breaking program correctness",
      "All inheritance is banned",
      "Subclasses may throw new checked exceptions arbitrarily widening contracts",
      "Private methods override public ones"], 0,
     "Subtypes must honor the behavioral contract of the base type; strengthening preconditions or weakening postconditions violates LSP."),
    ("software-development", "Software Development", "hard", "theory",
     "Dependency Inversion Principle suggests:",
     ["High-level modules depend on abstractions, not concrete low-level details",
      "Main() must import every concrete class",
      "Databases must be hard-coded in UI",
      "Globals are preferred over injection"], 0,
     "Depend on interfaces/abstractions; details implement those abstractions. Enables testability and flexibility."),
]


def build_question(row):
    cat, topic, diff, qtype, question, options, answer, explanation = row[:8]
    q = {
        "category": cat,
        "topic": topic,
        "difficulty": diff,
        "type": qtype,
        "question": question,
        "options": options,
        "answer": answer,
        "explanation": explanation,
    }
    if len(row) > 8 and row[8]:
        q["code"] = row[8]
    return q


def main():
    assert len(QUESTIONS) == 60, f"expected 60 questions, got {len(QUESTIONS)}"

    questions = [build_question(r) for r in QUESTIONS]

    diff_counts = {}
    cat_counts = {}
    for q in questions:
        diff_counts[q["difficulty"]] = diff_counts.get(q["difficulty"], 0) + 1
        cat_counts[q["category"]] = cat_counts.get(q["category"], 0) + 1

    assert diff_counts == {"easy": 20, "medium": 25, "hard": 15}, diff_counts
    assert all(cat_counts.get(c, 0) == 10 for c in [
        "core-java", "dbms", "backend", "docker", "angular", "software-development"
    ]), cat_counts

    payload = {
        "id": "test-01",
        "title": "Comprehensive Test 1 — Mixed Difficulty",
        "toughness": "Mixed — Easy, Medium & Hard",
        "durationMinutes": 60,
        "questions": questions,
    }

    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(questions)} questions)")
    print("difficulty:", diff_counts)
    print("category:", cat_counts)


if __name__ == "__main__":
    main()
