#!/usr/bin/env python3
"""Generate phase-06 through phase-09 MCQ JSON files (42 questions each)."""
import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data"


def q(topic, qtype, question, options, answer, explanation, code=None):
    item = {
        "topic": topic,
        "type": qtype,
        "question": question,
        "options": options,
        "answer": answer,
        "explanation": explanation,
    }
    if code:
        item["code"] = code
    return item


PHASE_06 = [
    q("JUnit", "theory", "What is the primary purpose of JUnit in Java projects?",
      ["Compile source code faster", "Write and run automated unit tests", "Deploy applications to servers", "Generate REST API documentation"],
      1, "JUnit is a unit-testing framework for Java. It lets you define test methods, assert expected outcomes, and run tests as part of build pipelines (Maven/Gradle) or the IDE."),
    q("JUnit", "annotation", "Which JUnit 5 annotation marks a method as a single test case?",
      ["@TestClass", "@RunWith", "@Test", "@Before"],
      2, "@Test (org.junit.jupiter.api.Test) identifies an executable test method. @BeforeEach/@AfterEach handle setup/teardown; @RunWith is JUnit 4 style."),
    q("JUnit", "annotation", "In JUnit 5, which annotation runs once before each test method in the class?",
      ["@BeforeAll", "@BeforeEach", "@Setup", "@Init"],
      1, "@BeforeEach executes before every @Test. @BeforeAll runs once per class before any test (often for expensive shared setup)."),
    q("JUnit", "code", "What does this assertion verify?",
      ["x is greater than y", "x equals y (with optional message)", "The test is ignored", "x is not null"],
      1, "assertEquals(expected, actual) checks value equality (using equals for objects). The optional message appears on failure.",
      code='assertEquals(42, result, "calculation failed");'),
    q("JUnit", "code", "How many times will the test method run?",
      ["Once", "Twice", "Three times", "Zero times (compile error)"],
      2, "@ParameterizedTest with @ValueSource(ints = {1, 2, 3}) runs the test once per provided value, so three executions.",
      code='@ParameterizedTest\n@ValueSource(ints = {1, 2, 3})\nvoid isPositive(int n) {\n  assertTrue(n > 0);\n}'),
    q("JUnit", "theory", "What is a key benefit of using @DisplayName on tests?",
      ["Skips slow tests automatically", "Provides human-readable names in reports", "Runs tests in parallel only", "Replaces @Test entirely"],
      1, "@DisplayName lets you describe tests clearly in IDE and CI output instead of showing only method names like testUserLogin_failureCase."),
    q("JUnit", "theory", "When should you prefer @Disabled on a test?",
      ["When the test must always run in CI", "When a test is temporarily broken or not applicable", "To speed up compilation", "To mock dependencies"],
      1, "@Disabled excludes a test from execution while keeping it in the codebase—useful for flaky tests under investigation or environment-specific cases."),
    q("JUnit", "code", "What exception-related assertion is most appropriate?",
      ["assertNull", "assertThrows", "assertTimeout", "assertAll"],
      1, "assertThrows(ExpectedException.class, () -> service.doWork()) verifies that the lambda throws the specified exception type.",
      code='assertThrows(IllegalArgumentException.class,\n  () -> service.parse(""));'),
    q("JUnit", "theory", "What does assertTimeout do in JUnit 5?",
      ["Asserts two values are equal within a time window", "Fails if the executable exceeds the given duration", "Waits forever for async code", "Measures code coverage"],
      1, "assertTimeout(Duration, Executable) fails the test if the code block runs longer than the limit—useful for performance regressions."),
    q("JUnit", "theory", "In a typical Maven project, where do unit tests live?",
      ["src/main/java", "src/test/java", "src/integration/java", "resources/test"],
      1, "Convention places production code under src/main/java and tests under src/test/java, compiled and run by the surefire plugin."),
    q("JUnit", "annotation", "Which annotation groups related tests and can apply tags at class level in JUnit 5?",
      ["@Suite", "@Nested", "@Group", "@CategoryOnly"],
      1, "@Nested creates inner test classes for hierarchical organization. @Tag filters tests; @Suite composes multiple test classes."),
    q("JUnit", "theory", "What is the difference between unit tests and integration tests in backend practice?",
      ["Unit tests always use a database; integration tests do not", "Unit tests isolate a small unit with mocks; integration tests wire real collaborators", "There is no difference", "Integration tests run only on Fridays"],
      1, "Unit tests focus on one class or method with dependencies stubbed. Integration tests verify components together (e.g., Spring context, database)."),
    q("JUnit", "code", "What will happen when this test runs (assuming list is empty)?",
      ["Test passes silently", "Test fails with AssertionFailedError", "Compilation error", "JUnit skips the test"],
      1, "assertFalse on an empty list returns true for isEmpty(), so the assertion fails because the condition is false.",
      code='List<String> list = new ArrayList<>();\nassertFalse(list.isEmpty());'),
    q("JUnit", "theory", "Why use assertAll in JUnit 5?",
      ["Run tests in parallel on all CPU cores", "Report all assertion failures in a group instead of stopping at the first", "Disable assertions", "Generate Mockito mocks"],
      1, "assertAll executes multiple assertions and reports every failure together—helpful when validating several fields of one object."),
    q("Mockito", "theory", "What problem does Mockito solve in unit testing?",
      ["Database migration", "Creating test doubles (mocks) for dependencies", "HTTP load balancing", "JSON serialization"],
      1, "Mockito lets you create mock objects that simulate collaborators, define behavior with when/thenReturn, and verify interactions."),
    q("Mockito", "code", "What does this line create?",
      ["A real UserRepository connected to H2", "A mock instance of UserRepository", "A spy of an existing bean", "A static mock for all tests"],
      1, "Mockito.mock(Class) or @Mock creates a proxy implementing the type; methods return defaults until stubbed.",
      code='UserRepository repo = mock(UserRepository.class);'),
    q("Mockito", "annotation", "Which JUnit 5 extension initializes @Mock fields automatically?",
      ["@ExtendWith(SpringExtension.class) only", "@ExtendWith(MockitoExtension.class)", "@RunWith(JUnit4.class)", "@EnableMocking"],
      1, "MockitoExtension (or @ExtendWith(MockitoExtension.class)) injects mocks and handles strict stubbing in JUnit 5 tests."),
    q("Mockito", "code", "When findById(1L) is called on the mock, what does it return?",
      ["null always", "Optional.of(user)", "Optional.empty()", "Throws exception"],
      1, "when(...).thenReturn(...) stubs the method. Here findById(1L) returns Optional.of(user); other arguments use default (empty Optional).",
      code='when(repo.findById(1L)).thenReturn(Optional.of(user));\nOptional<User> u = repo.findById(1L);'),
    q("Mockito", "code", "What does verify(repo).save(user) assert?",
      ["save was never called", "save was called exactly once with this user", "save returns user", "repo is not a mock"],
      1, "verify checks interaction: that save(user) was invoked on the mock. Use times(n), never(), etc. for finer control.",
      code="service.register(user);\nverify(repo).save(user);"),
    q("Mockito", "theory", "What is the difference between mock and spy in Mockito?",
      ["Spy calls real methods by default; mock does not unless stubbed", "Mock always hits the database", "Spy cannot verify interactions", "They are identical"],
      0, "A spy wraps a real object and delegates to it unless a method is stubbed. A mock has no real implementation—all methods are stubbed or return defaults."),
    q("Mockito", "code", "What is wrong with stubbing a void method this way?",
      ["Nothing; it is correct", "void methods use doNothing()/doThrow() with when or doAnswer", "You must use @Spy", "verify cannot be used"],
      1, "For void methods use doThrow(...).when(mock).method() or doNothing().when(mock).method() because thenReturn does not apply to void.",
      code='when(emailService.send(any())).thenReturn(true); // void send()'),
    q("Mockito", "theory", "What does ArgumentMatchers.anyString() match?",
      ["Only null", "Only empty string", "Any String including null (with nullable matchers)", "Only literal \"any\""],
      2, "anyString() matches any String argument when stubbing or verifying. Use nullable(Class) when null must be accepted explicitly."),
    q("Mockito", "annotation", "What does @InjectMocks do?",
      ["Injects Spring beans from application context", "Creates an instance and injects @Mock/@Spy fields into it", "Mocks static methods only", "Starts embedded database"],
      1, "@InjectMocks constructs the class under test and tries to inject mocks into constructor/setters/fields—ideal for testing a service with mocked DAO."),
    q("Mockito", "theory", "Why avoid mocking types you do not own (e.g., JDK or third-party concrete classes)?",
      ["It is illegal in Java", "It couples tests to implementation details and can break on upgrades; prefer wrapping or interfaces", "Mockito cannot mock interfaces", "Mocks are slower than real objects always"],
      1, "Mocking concrete libraries you do not control is fragile. Prefer your own interfaces or adapters so tests stay stable."),
    q("Mockito", "code", "How many times was deleteAll called after this test logic?",
      ["0", "1", "2", "3"],
      2, "verify(repo, times(2)).deleteAll() passes only if deleteAll was invoked twice. The service code must call it twice.",
      code='verify(repo, times(2)).deleteAll();'),
    q("Hibernate ORM", "theory", "What role does Hibernate play in a Java application?",
      ["A web server", "An ORM that maps Java objects to relational tables", "A message broker", "A build tool"],
      1, "Hibernate implements JPA-style object-relational mapping: entities become rows, associations become foreign keys, and HQL/Criteria query objects."),
    q("Hibernate ORM", "theory", "What is the Hibernate Session in classic API terms?",
      ["A browser HTTP session", "A single-threaded workspace between app and database for CRUD and queries", "A JWT token store", "A Git branch"],
      1, "Session (now often EntityManager in JPA) tracks persistent entities, manages transactions, and synchronizes state with the database."),
    q("Hibernate ORM", "theory", "What does SessionFactory represent?",
      ["One database row", "A thread-safe factory expensive to create; produces Sessions/EntityManagers", "A REST controller", "A Mockito mock"],
      1, "SessionFactory is built once from configuration (XML or properties) and is heavy to create. It spawns lightweight Session instances per unit of work."),
    q("Hibernate ORM", "theory", "Which configuration file is commonly used for Hibernate settings in older setups?",
      ["application.yml only", "hibernate.cfg.xml or persistence.xml", "pom.xml", "Dockerfile"],
      1, "hibernate.cfg.xml (native Hibernate) or META-INF/persistence.xml (JPA) define datasource, dialect, and mapping resources."),
    q("Hibernate ORM", "theory", "What is a Hibernate dialect used for?",
      ["UI theming", "Generating SQL appropriate to the database vendor", "Encrypting passwords", "Mocking repositories"],
      1, "Dialect translates HQL/Criteria and DDL to vendor-specific SQL (MySQL, PostgreSQL, etc.) and handles pagination syntax differences."),
    q("Hibernate ORM", "theory", "What does hbm2ddl.auto=update typically do in development?",
      ["Deletes all data on startup", "Adjusts schema to match mappings (adds columns/tables; risky in production)", "Disables Hibernate", "Creates only indexes"],
      1, "update compares mappings to schema and applies incremental DDL. Never rely on it blindly in production—use migrations (Flyway/Liquibase)."),
    q("Hibernate ORM", "theory", "How does Hibernate relate to JPA?",
      ["They are unrelated", "JPA is a specification; Hibernate is a popular implementation", "JPA replaces JDBC entirely", "Hibernate only works with MongoDB"],
      1, "JPA defines annotations and EntityManager API. Hibernate implements JPA and adds proprietary features (e.g., @Formula, extra fetch modes)."),
    q("Entities", "annotation", "Which annotation marks a class as a JPA/Hibernate entity?",
      ["@TableOnly", "@Entity", "@Component", "@Repository"],
      1, "@Entity (javax/jakarta.persistence.Entity) declares a persistent class. @Table optionally names the table; @Id marks primary key."),
    q("Entities", "annotation", "What does @Id on a field indicate?",
      ["The field is optional", "Primary key column for the entity", "Foreign key only", "Transient field"],
      1, "@Id designates the primary key. Combine with @GeneratedValue for identity/sequence/table strategies."),
    q("Entities", "annotation", "Which strategy generates numeric keys using database IDENTITY columns?",
      ["GenerationType.SEQUENCE", "GenerationType.IDENTITY", "GenerationType.UUID", "GenerationType.MANUAL only"],
      1, "IDENTITY uses auto-increment (MySQL AUTO_INCREMENT, SQL Server IDENTITY). SEQUENCE uses a separate sequence object common in Oracle/PostgreSQL."),
    q("Entities", "annotation", "What does @Column(name = \"email_addr\") do?",
      ["Creates a new table", "Maps the field to column email_addr", "Marks field read-only in UI", "Enables caching"],
      1, "@Column customizes column name, length, nullable, unique constraints. Default name is field name unless overridden."),
    q("Entities", "theory", "What is the difference between transient and persistent entity state?",
      ["Transient is in memory only, not associated with a Session; persistent is managed and tracked", "They are the same", "Persistent means deleted", "Transient means cached in Redis"],
      0, "New objects are transient until persisted (save). Persistent entities are attached to a persistence context; detached after Session closes."),
    q("Mappings", "annotation", "Which mapping describes a many-to-one association from Order to Customer?",
      ["@OneToMany on Order.customer", "@ManyToOne on Order.customer", "@ManyToMany on Order only", "@Embedded on Customer"],
      1, "@ManyToOne places the foreign key on the owning side (Order table has customer_id). @OneToMany is the inverse on Customer."),
    q("Mappings", "annotation", "In @OneToMany(mappedBy = \"department\"), what does mappedBy mean?",
      ["This side owns the foreign key", "The other entity owns the relationship; this is the inverse side", "Maps to a database view", "Uses eager fetch always"],
      1, "mappedBy points to the field on the child that owns the FK. The child (@ManyToOne) side owns the association in bidirectional mappings."),
    q("Mappings", "annotation", "What does @JoinColumn specify?",
      ["Java package name", "Foreign key column details on the owning side", "HTTP path", "Cache region name"],
      1, "@JoinColumn(name = \"dept_id\") defines FK column name and optional referencedColumnName for @ManyToOne/@OneToOne owning side."),
    q("Mappings", "annotation", "When should you use @Embedded and @Embeddable?",
      ["For many-to-many only", "To map a value object (e.g., Address) into columns of the parent table", "To create stored procedures", "For REST DTOs only"],
      1, "@Embeddable types flatten into the parent table columns (street, city) without a separate Address table—good for composite value objects."),
    q("Mappings", "annotation", "What does @ManyToMany with @JoinTable define?",
      ["A single-column primary key", "A join table linking two entities", "A Hibernate cache region", "A Spring bean"],
      1, "@JoinTable names the link table and join columns for both sides. Many-to-many often needs explicit ownership and fetch strategy."),
]

PHASE_07 = [
    q("Hibernate Fetch", "theory", "What is the N+1 select problem?",
      ["One query returns N tables", "Loading N parent rows triggers N additional queries for children", "Using N databases", "Having N+1 indexes"],
      1, "E.g., fetch 100 Orders (1 query) then lazy-load each Order's items (100 queries). Fix with join fetch, @EntityGraph, or batch size."),
    q("Hibernate Fetch", "annotation", "What does FetchType.LAZY mean for @OneToMany?",
      ["Collection loads immediately with parent", "Collection loads when accessed and session is open", "No SQL is ever run", "Uses only native queries"],
      1, "LAZY proxies the collection until accessed. Access outside an open session causes LazyInitializationException unless initialized earlier."),
    q("Hibernate Fetch", "annotation", "What does FetchType.EAGER imply?",
      ["Always better for performance", "Associated data loaded with parent; can cause large joins or cartesian products", "Disables SQL", "Only works with Mockito"],
      1, "EAGER fetches association with parent load. Convenient but can over-fetch and hurt performance—often prefer LAZY + explicit fetch plans."),
    q("Hibernate Fetch", "code", "Which JPQL keyword reduces N+1 when loading authors and books?",
      ["GROUP BY only", "JOIN FETCH", "DISTINCT DELETE", "CACHE ONLY"],
      1, "JOIN FETCH loads association in the same query: SELECT a FROM Author a JOIN FETCH a.books"),
    q("Hibernate Fetch", "theory", "What is Hibernate batch fetching (e.g., @BatchSize)?",
      ["Deleting in batches only", "Loading multiple lazy collections or entities in fewer SQL round-trips", "HTTP batch API", "JUnit batch tests"],
      1, "@BatchSize on class or collection lets Hibernate load multiple uninitialized proxies/collections in one IN-clause query."),
    q("Hibernate Cascade", "theory", "What does CascadeType.REMOVE do?",
      ["Removes only the parent row", "Deleting parent may delete associated children per mapping", "Removes the database", "Removes mocks"],
      1, "REMOVE cascades delete to associated entities—dangerous on @ManyToOne if misapplied. OrphanRemoval handles unlinked children in @OneToMany."),
    q("Hibernate Cascade", "annotation", "What is orphanRemoval = true on @OneToMany?",
      ["Children without parent reference are deleted when relationship changes", "Prevents all deletes", "Removes Hibernate cache", "Same as @Transactional"],
      0, "orphanRemoval deletes child rows removed from the parent's collection when the unit of work flushes—distinct from cascade REMOVE semantics."),
    q("Hibernate Cascade", "theory", "Which cascade type propagates merge from parent to children?",
      ["CascadeType.DETACH only", "CascadeType.MERGE", "CascadeType.REFRESH only for HTTP", "CascadeType.SECURITY"],
      1, "MERGE reattaches detached graphs: merging parent can merge children if cascade includes MERGE."),
    q("Hibernate Cache", "theory", "What is the first-level (L1) cache in Hibernate?",
      ["Cluster-wide Redis", "Session-scoped persistence context; identity map for entities in that Session", "Browser cache", "CDN"],
      1, "Each Session/EntityManager has an L1 cache: repeated get by id within same transaction returns same instance without extra SELECT."),
    q("Hibernate Cache", "theory", "What does second-level (L2) cache require?",
      ["Nothing; enabled by default for all entities", "Provider (e.g., Ehcache), entity/cache region configuration, often read-mostly data", "Only @Mock beans", "Spring MVC"],
      1, "L2 is SessionFactory-scoped shared cache across sessions. Configure cache provider, @Cacheable entities, and concurrency strategy."),
    q("Hibernate Cache", "theory", "When is query cache useful?",
      ["For every write-heavy query", "When identical queries repeat with same parameters and underlying data changes infrequently", "Never with JPA", "Only in unit tests"],
      1, "Query cache stores result ids; still needs L2 for entities. Invalidate carefully when data changes or use short TTL."),
    q("Hibernate Cache", "annotation", "What does @Cache(usage = CacheConcurrencyStrategy.READ_ONLY) suggest?",
      ["Entity is updated every second", "Data is immutable after insert; safe optimized read cache", "Disables L1 cache", "Enables write-through only"],
      1, "READ_ONLY suits reference data never updated. READ_WRITE/NONSTRICT_READ_WRITE handle updates with versioning considerations."),
    q("Spring DI", "theory", "What is Dependency Injection in Spring?",
      ["Developers always use new in constructors manually", "Spring container provides dependencies to objects instead of them creating collaborators", "A SQL feature", "JUnit feature"],
      1, "IoC container wires beans via constructor, setter, or field injection based on configuration (XML, annotations, Java config)."),
    q("Spring DI", "theory", "Which injection style is generally recommended in modern Spring?",
      ["Field injection only", "Constructor injection for required dependencies", "Static injection", "ThreadLocal injection only"],
      1, "Constructor injection makes dependencies explicit, eases unit testing, and allows immutable fields. Field injection is harder to test without Spring."),
    q("Spring Beans", "annotation", "What does @Component stereotype indicate?",
      ["A database entity", "A Spring-managed bean detected by component scanning", "A JUnit test", "A servlet filter only"],
      1, "@Component is generic stereotype. Specializations: @Service, @Repository, @Controller."),
    q("Spring Beans", "annotation", "Difference between @Component and @Bean?",
      ["No difference", "@Component on class; @Bean on method in @Configuration defining factory-created instance", "@Bean only for entities", "@Component only in XML"],
      1, "@Bean methods programmatically register objects (third-party classes). @Component marks your class for classpath scanning."),
    q("Spring Beans", "annotation", "What does @Autowired do?",
      ["Starts the JVM", "Injects matching bean by type (and qualifier/name if needed)", "Creates database tables", "Compiles templates"],
      1, "@Autowired resolves dependencies from the ApplicationContext. Use @Qualifier or @Primary when multiple beans of same type exist."),
    q("Spring Beans", "annotation", "When are two beans of the same interface ambiguous?",
      ["Never", "When multiple implementations exist without @Primary or @Qualifier", "Only in JUnit", "Only with @Entity"],
      1, "Spring throws NoUniqueBeanDefinitionException unless @Primary marks default or @Qualifier disambiguates injection point."),
    q("Spring Beans", "annotation", "What does @Scope(\"prototype\") mean?",
      ["One instance per application", "New instance created each time bean is requested/injected (prototype)", "Bean is not managed", "Runs only in tests"],
      1, "Default singleton = one shared instance. Prototype creates a new object per getBean/injection—watch memory with long-lived singletons holding prototypes."),
    q("Spring Lifecycle", "theory", "What happens during Spring bean initialization order broadly?",
      ["Random order", "Instantiate → populate properties → BeanPostProcessor before init → @PostConstruct/custom init → ready", "Only @Test runs", "Deploy to Eureka first"],
      1, "Container creates bean, injects dependencies, applies BeanPostProcessors, calls initialization callbacks (@PostConstruct, InitializingBean), then bean is usable."),
    q("Spring Lifecycle", "annotation", "Which annotation marks a method to run after dependency injection?",
      ["@PreDestroy", "@PostConstruct", "@BeforeEach", "@Scheduled only"],
      1, "@PostConstruct (javax/jakarta.annotation) runs after injection. @PreDestroy runs on shutdown for cleanup."),
    q("Spring Lifecycle", "theory", "What is a BeanPostProcessor?",
      ["A JPA repository", "Callback hook to customize beans before/after initialization", "HTTP interceptor only", "Mockito plugin"],
      1, "BeanPostProcessors can wrap or modify beans (e.g., @Autowired processing, AOP proxies) in postProcessBefore/AfterInitialization."),
    q("Spring Config", "annotation", "What does @Configuration provide?",
      ["Marks test class", "Declares class as source of @Bean definitions and CGLIB-enhanced singleton semantics", "Enables Hibernate only", "Disables component scan"],
      1, "@Configuration classes define @Bean methods. Full @Configuration CGLIB-proxies @Bean methods so singletons call each other correctly."),
    q("Spring Config", "annotation", "What does @ComponentScan do?",
      ["Scans hard drives", "Registers @Component and stereotype classes in specified base packages", "Runs SQL scripts", "Opens HTTP port"],
      1, "@ComponentScan on @SpringBootApplication or @Configuration tells Spring where to find annotated beans."),
    q("Spring Config", "theory", "What is ApplicationContext?",
      ["A Git repo", "Spring IoC container providing bean factory, events, internationalization, and more", "A database connection", "Mockito context"],
      1, "ApplicationContext extends BeanFactory with enterprise features: event publication, resource loading, and environment abstraction."),
    q("Spring DI", "code", "Which constructor will Spring use for injection?",
      ["No constructor; fails", "The single constructor with parameters (implicit autowire in Spring 4.3+)", "Only default no-arg if present", "Random constructor"],
      1, "If a class has one constructor, Spring autowires it without @Autowired. Multiple constructors need @Autowired on chosen one.",
      code='@Service\npublic class OrderService {\n  private final OrderRepository repo;\n  public OrderService(OrderRepository repo) {\n    this.repo = repo;\n  }\n}'),
    q("Spring Beans", "theory", "What is the default scope for Spring beans?",
      ["prototype", "singleton", "request", "session always"],
      1, "Unless @Scope specifies otherwise, beans are singletons within the container (one instance per Spring context, not JVM-global static)."),
    q("Hibernate Fetch", "theory", "What causes LazyInitializationException?",
      ["Using @Autowired", "Accessing uninitialized lazy association outside persistence context/session", "Using @Valid", "Running JUnit"],
      1, "Close session then call order.getItems().size() → exception. Fix: fetch join, @Transactional service method, or DTO projection."),
    q("Hibernate Fetch", "annotation", "What does @EntityGraph accomplish?",
      ["Defines REST routes", "Declares fetch plan (attributes to load) for repository query", "Replaces @Entity", "Configures RabbitMQ"],
      1, "@EntityGraph on Spring Data method specifies which associations to fetch eagerly for that query without changing global EAGER mapping."),
    q("Spring Lifecycle", "annotation", "What does @PreDestroy indicate?",
      ["Run before bean creation", "Cleanup hook before bean removal from container", "Run before each HTTP request always", "JUnit teardown"],
      1, "@PreDestroy methods release resources (close connections) when the context shuts down or bean is discarded."),
    q("Spring DI", "annotation", "What is @Qualifier used for?",
      ["Qualify test scores", "Select specific bean when multiple candidates share a type", "Validate DTOs", "Enable caching"],
      1, "@Qualifier(\"emailNotifier\") pairs with @Autowired to inject the named bean implementation."),
    q("Spring Beans", "annotation", "Why use @Repository stereotype?",
      ["Marks MVC controller", "Indicates persistence layer; enables exception translation to DataAccessException", "Creates Feign client", "JWT signing"],
      1, "@Repository is semantic @Component plus persistence exception translation via PersistenceExceptionTranslationPostProcessor."),
    q("Hibernate Cascade", "theory", "Should you cascade ALL on every association?",
      ["Yes, always", "No—cascade only operations you intend to propagate; misuse causes accidental deletes/updates", "Only on @Controller", "Required by JPA spec always"],
      1, "CascadeType.ALL propagates persist, merge, remove, refresh, detach. Apply narrowly—especially avoid careless REMOVE on wide graphs."),
    q("Spring Config", "theory", "Difference between BeanFactory and ApplicationContext?",
      ["Identical", "ApplicationContext adds events, i18n, AOP autoproxy, and is what Spring Boot uses", "BeanFactory is for Angular", "ApplicationContext cannot load beans"],
      1, "BeanFactory is minimal IoC. ApplicationContext is the rich container used in practice (AnnotationConfigApplicationContext, etc.)."),
    q("Spring DI", "theory", "What is inversion of control (IoC)?",
      ["Database controls the UI", "Framework controls object creation and wiring; app code receives dependencies", "Controllers invert HTTP", "Caches invert keys"],
      1, "IoC means the container manages lifecycle and dependencies rather than each class doing new Collaborator() itself."),
    q("Hibernate Cache", "theory", "Why cache immutable reference data (countries, codes)?",
      ["Writes are frequent", "Reduces database load for read-heavy stable data", "Required for Mockito", "Replaces transactions"],
      1, "L2 cache shines for rarely changed lookup tables accessed across many requests—always tune eviction and consistency."),
    q("Spring Lifecycle", "theory", "What does DisposableBean interface provide?",
      ["Initialization callback", "destroy() callback for cleanup; prefer @PreDestroy in modern code", "JWT validation", "Feign fallback"],
      1, "Implementing DisposableBean defines destroy(). @PreDestroy is the annotation-based equivalent preferred in application code."),
    q("Spring Beans", "code", "How many PaymentService beans exist at runtime (default scope)?",
      ["Three", "One singleton shared", "Zero", "One per injection point always new"],
      1, "@Service defaults to singleton: one instance in the context; all injection points share it unless @Scope prototype.",
      code='@Service\nclass PaymentService {}\n// injected in OrderService and InvoiceService'),
    q("Hibernate Fetch", "theory", "What is select fetch vs join fetch tradeoff?",
      ["No tradeoff", "Join fetch: one query, risk of duplicate rows; select: extra queries but simpler result set", "Join always forbidden", "Select always one query"],
      1, "JOIN FETCH can duplicate parent rows with multiple children (use DISTINCT). SELECT fetch uses separate queries—batching mitigates N+1."),
    q("Spring DI", "annotation", "What does @Primary resolve?",
      ["Primary key in DB", "Default bean when multiple implementations match injection by type", "First test method", "Main class only"],
      1, "@Primary on one @Service implementation makes it the default when autowiring PaymentGateway without @Qualifier."),
    q("Spring Config", "annotation", "What does @PropertySource add?",
      ["HTTP routes", "Loads properties file into Spring Environment", "Mockito stubs", "JPA entities"],
      1, "@PropertySource(\"classpath:app.properties\") exposes keys for @Value and Environment.getProperty()."),
    q("Hibernate Cascade", "annotation", "CascadeType.PERSIST vs REMOVE— which is safer to use widely?",
      ["REMOVE on all relations", "PERSIST on parent-child composition where child has no meaning alone", "Neither exists", "Both on @ManyToOne from child to parent always"],
      1, "PERSIST on composition (Order-LineItem) is common. REMOVE cascade from child to parent @ManyToOne is usually wrong and dangerous."),
]

PHASE_08 = [
    q("Spring MVC", "theory", "What pattern does Spring MVC implement for web apps?",
      ["Singleton only", "Model-View-Controller separation of concerns", "Microservices registry", "ORM only"],
      1, "DispatcherServlet routes requests to @Controller handlers, binds data to Model, and resolves Views (or REST body)."),
    q("Spring MVC", "annotation", "Which annotation marks a class as a web controller in Spring MVC?",
      ["@Entity", "@Controller or @RestController", "@Repository", "@FeignClient"],
      1, "@Controller returns view names; @RestController = @Controller + @ResponseBody for JSON/XML APIs."),
    q("Spring MVC", "annotation", "What does @RequestMapping on a class do?",
      ["Starts transaction", "Prefixes URL paths for all handler methods in the class", "Creates JPA table", "Enables cache"],
      1, "Class-level @RequestMapping(\"/api/orders\") combines with method-level mappings to form full paths."),
    q("Spring MVC", "annotation", "Difference between @GetMapping and @RequestMapping(method=GET)?",
      ["No difference in behavior for GET", "@GetMapping is composed shortcut; same HTTP GET mapping", "@GetMapping only works in Boot", "@RequestMapping cannot use GET"],
      1, "@GetMapping is a specialized @RequestMapping with method GET—cleaner and preferred in modern Spring."),
    q("Spring MVC", "code", "What will this endpoint return path variable id for GET /products/7?",
      ["null", "\"7\" as String", "7L only if Long declared", "Error always"],
      1, "@PathVariable binds URI template variable. Type conversion can parse \"7\" to Long if parameter is Long id.",
      code='@GetMapping("/products/{id}")\npublic Product get(@PathVariable Long id) { ... }'),
    q("Spring MVC", "code", "How is query parameter page bound?",
      ["From request body JSON only", "@RequestParam name=page from query string ?page=2", "From path only", "From header only"],
      1, "@RequestParam(\"page\") int page reads ?page=2. defaultValue and required=false are optional attributes.",
      code='@GetMapping("/items")\npublic List<Item> list(@RequestParam(defaultValue="0") int page) { ... }'),
    q("Model", "theory", "What is the Model in Spring MVC used for?",
      ["Database schema", "Passing attributes from controller to view (server-side rendering)", "JWT storage", "Docker image"],
      1, "Model (or ModelAndView) holds request-scoped attributes for Thymeleaf/JSP views. REST APIs often return DTOs directly without Model."),
    q("Model", "code", "In Thymeleaf view, how is user accessed if added as below?",
      ["${user} from model attribute name", "Only via session", "Cannot pass objects", "Via @Autowired"],
      1, "model.addAttribute(\"user\", user) exposes user in template as ${user} (name matches attribute key).",
      code='model.addAttribute("user", user);\nreturn "profile"; // resolves profile.html'),
    q("Validation", "annotation", "What does @Valid on a controller parameter do?",
      ["Starts Hibernate session", "Triggers Bean Validation (JSR-380) on the object", "Creates mock", "Parses JWT"],
      1, "@Valid runs constraints like @NotNull, @Size on the argument. Combine with BindingResult to handle errors without exception."),
    q("Validation", "annotation", "Which annotation rejects null and blank strings on a field?",
      ["@Lazy", "@NotBlank", "@Fetch", "@Autowired"],
      1, "@NotBlank (javax/jakarta.validation) ensures trimmed length > 0. @NotNull allows empty string; @NotEmpty for collections."),
    q("Validation", "code", "How should validation errors be handled when using @Valid without exception?",
      ["Ignore errors", "Check BindingResult.hasErrors() after @Valid", "Delete the database", "Use @PreAuthorize"],
      1, "Signature: method(@Valid @RequestBody Dto dto, BindingResult br). If br.hasErrors(), return 400 with field errors.",
      code='public ResponseEntity<?> create(@Valid @RequestBody UserDto dto,\n  BindingResult result) {\n  if (result.hasErrors()) return badRequest(result);\n  ...\n}'),
    q("Exception Handling", "annotation", "What does @ExceptionHandler on a controller method do?",
      ["Handles all JVM errors", "Maps specific exceptions to response for that controller", "Replaces @Controller", "Enables Feign"],
      1, "@ExceptionHandler(IllegalArgumentException.class) in @ControllerAdvice or controller returns structured error response."),
    q("Exception Handling", "annotation", "Why use @ControllerAdvice?",
      ["Per-request caching only", "Global exception handling and model binding across controllers", "Database migration", "RabbitMQ config"],
      1, "@ControllerAdvice centralizes @ExceptionHandler, @InitBinder, @ModelAttribute methods for all or selected controllers."),
    q("Exception Handling", "code", "What HTTP status fits ResourceNotFoundException handler returning NOT_FOUND?",
      ["200", "404", "500 always", "301"],
      1, "@ResponseStatus(HttpStatus.NOT_FOUND) or ResponseEntity.status(404) signals client the resource id does not exist.",
      code='@ExceptionHandler(ResourceNotFoundException.class)\n@ResponseStatus(HttpStatus.NOT_FOUND)\npublic ErrorDto handleNotFound(ResourceNotFoundException ex) { ... }'),
    q("DTOs", "theory", "Why use DTOs instead of exposing JPA entities in REST APIs?",
      ["DTOs are slower always", "Decouple persistence model, control serialized fields, avoid lazy-load and circular JSON", "JPA forbids entities", "DTOs replace database"],
      1, "Entities carry persistence annotations and associations; DTOs expose stable API contracts and prevent leaking internal structure."),
    q("DTOs", "theory", "What is a common way to map Entity to DTO?",
      ["Manual mapping, MapStruct, or ModelMapper", "Only Hibernate automatic", "Copy file in OS", "JWT decode"],
      0, "Teams use explicit mappers (MapStruct compile-time), libraries, or hand-written conversion in service layer."),
    q("Pagination", "theory", "What does Spring Data Pageable represent?",
      ["Single entity id", "Request for a page: page number, size, and optional Sort", "Full table dump", "Cache key only"],
      1, "Pageable encapsulates page, size, sort. Repository methods return Page<T> with content and total elements."),
    q("Pagination", "code", "Which repository method signature supports pagination?",
      ["findAll() only", "Page<Product> findAll(Pageable pageable)", "void deleteAll(Pageable)", "Product findPage(int)"],
      1, "Spring Data derives queries; Pageable adds LIMIT/OFFSET (or cursor) and count query for totals.",
      code='Page<Product> findByCategory(String cat, Pageable pageable);'),
    q("Pagination", "theory", "What metadata does Page<T> typically include?",
      ["Only list content", "content, totalElements, totalPages, number, size", "JWT claims", "SQL dialect"],
      1, "Page interface provides getContent(), getTotalElements(), getTotalPages(), isFirst(), isLast() for API pagination wrappers."),
    q("Swagger", "theory", "What is OpenAPI (Swagger) used for in Spring projects?",
      ["ORM mapping", "Describing REST API contract; generating UI docs and clients", "Unit testing only", "Message queuing"],
      1, "OpenAPI documents paths, schemas, security. springdoc-openapi exposes /swagger-ui and /v3/api-docs."),
    q("Swagger", "annotation", "Which springdoc annotation documents operation summary on a controller method?",
      ["@Operation", "@Entity", "@Transactional", "@RabbitListener"],
      0, "@Operation(summary = \"...\") from io.swagger.v3.oas.annotations documents individual endpoints in OpenAPI."),
    q("Swagger", "annotation", "What does @Schema on a DTO field control?",
      ["SQL column type only", "API documentation: description, example, required", "Bean scope", "Fetch type"],
      1, "@Schema(description, example, requiredMode) enriches generated OpenAPI for clients and Swagger UI."),
    q("Spring MVC", "annotation", "What does @RequestBody do?",
      ["Writes HTML view", "Deserializes HTTP body (JSON) to Java object via HttpMessageConverter", "Reads path variable", "Injects Spring bean"],
      1, "@RequestBody uses Jackson (for JSON) to map body to parameter type. Often paired with @Valid."),
    q("Spring MVC", "annotation", "What does @ResponseBody do?",
      ["Returns view name", "Serializes return value directly to HTTP response body", "Starts transaction", "Validates JWT"],
      1, "@ResponseBody selects HttpMessageConverter to write JSON/XML. @RestController applies it class-wide."),
    q("Spring MVC", "theory", "What is DispatcherServlet's role?",
      ["JPA provider", "Front controller delegating to handler mappings, adapters, and view resolvers", "RabbitMQ broker", "Docker daemon"],
      1, "DispatcherServlet is the single entry servlet mapping requests to @RequestMapping handlers and handling response rendering."),
    q("Validation", "annotation", "What does @Email validate?",
      ["Password strength", "String matches email format per Bean Validation", "Database email uniqueness", "SMTP send"],
      1, "@Email checks basic email pattern (configurable). Uniqueness still needs service/repository check."),
    q("Validation", "theory", "What is Method Validation (@Validated on class)?",
      ["Validates HTTP headers only", "Validates method parameters and return values on service layer with @Valid constraints", "Hibernate only feature", "JUnit plugin"],
      1, "@Validated on @Service enables @NotNull parameters on methods via AOP MethodValidationPostProcessor."),
    q("Exception Handling", "theory", "When is @ResponseStatus insufficient compared to ResponseEntity?",
      ["Never", "When you need custom headers, body shape, or dynamic status per call", "Always", "For GET only"],
      1, "ResponseEntity lets you build status, headers, and body programmatically; @ResponseStatus is declarative fixed status."),
    q("DTOs", "code", "Why avoid returning List<Entity> with bidirectional @OneToMany in JSON?",
      ["Faster serialization", "Infinite recursion / huge graphs (Jackson JsonIgnore or DTOs needed)", "Illegal in Spring", "Entities cannot serialize"],
      1, "Parent→children→parent causes StackOverflow or huge payloads. Use DTOs or @JsonIgnore on back-reference."),
    q("Pagination", "code", "Client sends GET /api/users?page=1&size=20&sort=name,asc. What binds sort?",
      ["Nothing", "Pageable or PageableDefault with Sort parameter", "Only @PathVariable", "@PreAuthorize"],
      1, "Spring MVC resolves Pageable from query params page, size, sort automatically when argument is present."),
    q("Swagger", "theory", "Where is springdoc OpenAPI JSON typically exposed?",
      ["/actuator/health only", "/v3/api-docs", "/h2-console", "/eureka"],
      1, "springdoc-openapi serves OpenAPI 3 JSON at /v3/api-docs and Swagger UI at /swagger-ui.html or /swagger-ui/index.html."),
    q("Spring MVC", "annotation", "What does @ModelAttribute on a method parameter do?",
      ["JWT claim", "Binds request parameters/form fields to object", "Creates singleton bean", "Enables L2 cache"],
      1, "@ModelAttribute binds query/form data to command object—common in traditional MVC forms, less in pure REST JSON."),
    q("Spring MVC", "theory", "Content negotiation in REST means?",
      ["Negotiating salary", "Selecting response format (JSON/XML) via Accept header or produces attribute", "Database lock", "Git merge"],
      1, "@GetMapping(produces = MediaType.APPLICATION_JSON_VALUE) limits mapping to clients accepting that media type."),
    q("Exception Handling", "annotation", "What does ProblemDetail (RFC 7807) provide in Spring 6+?",
      ["ORM mapping file", "Standardized machine-readable error body (type, title, status, detail)", "Feign client", "Queue name"],
      1, "ProblemDetail helps consistent API errors instead of ad-hoc JSON shapes across services."),
    q("Validation", "annotation", "What does @Size(min=8) on password enforce?",
      ["Email format", "String length or collection size constraints", "Primary key", "HTTP timeout"],
      1, "@Size validates character length for strings or element count for collections per min/max attributes."),
    q("DTOs", "theory", "Record types as DTOs in Java 16+ offer?",
      ["Mutable setters by default", "Compact immutable data carriers good for API responses", "JPA entity replacement always", "Automatic DB schema"],
      1, "Records provide equals/hashCode/toString and accessors—nice for read-only API DTOs with validation on compact constructors."),
    q("Spring MVC", "code", "What status should POST /orders return on successful creation with body?",
      ["200 OK always", "201 Created with Location header often", "204 always", "500"],
      1, "REST convention: 201 Created for new resource; Location header may point to GET /orders/{id}.",
      code="return ResponseEntity.created(uri).body(orderDto);"),
    q("Swagger", "annotation", "What does @Tag on a controller class do?",
      ["JPA table name", "Groups endpoints in OpenAPI documentation", "Rabbit exchange", "Security role"],
      1, "@Tag(name = \"Orders\") organizes operations in Swagger UI sidebar sections."),
    q("Pagination", "theory", "Offset pagination drawback on large tables?",
      ["Too fast", "Deep pages (high OFFSET) scan many rows and slow down", "Cannot sort", "Breaks JSON"],
      1, "OFFSET 100000 LIMIT 20 still scans skipped rows. Cursor/keyset pagination scales better for infinite feeds."),
    q("Exception Handling", "theory", "Should generic Exception handler expose stack traces to clients?",
      ["Yes, always in production", "No—log server-side; return safe message to avoid information leakage", "Required by OpenAPI", "Only in dev with care"],
      1, "Production APIs return generic errors; detailed traces belong in logs and monitoring, not public responses."),
    q("Spring MVC", "annotation", "What does consumes attribute on @PostMapping specify?",
      ["Response type", "Required Content-Type of request (e.g., application/json)", "Database dialect", "Cache region"],
      1, "consumes = APPLICATION_JSON_VALUE maps only when client sends matching Content-Type header."),
    q("Validation", "theory", "Custom constraint in Bean Validation requires?",
      ["Only @NotNull", "@Constraint annotation + ConstraintValidator implementation", "@Controller only", "pom packaging war"],
      1, "Define annotation annotated with @Constraint(validatedBy=...) and implement ConstraintValidator<A, T> for logic."),
]

PHASE_09 = [
    q("Spring Boot REST", "theory", "What does spring-boot-starter-web bring to a project?",
      ["Only JPA", "Spring MVC, embedded Tomcat, Jackson for REST", "Only RabbitMQ", "Angular CLI"],
      1, "starter-web bundles MVC, Jackson JSON, validation API, and embedded servlet container for REST applications."),
    q("Spring Boot REST", "annotation", "What does @SpringBootApplication combine?",
      ["@Entity and @Table", "@Configuration, @EnableAutoConfiguration, @ComponentScan", "@Feign and @Eureka", "@Test only"],
      1, "@SpringBootApplication is a convenience meta-annotation enabling auto-config and component scanning from the main class package."),
    q("Spring Boot REST", "theory", "What is spring-boot-starter-data-jpa?",
      ["CSS framework", "Spring Data JPA, Hibernate, JDBC starter for repositories", "Security only", "Gateway router"],
      1, "It pulls Hibernate as JPA provider, Spring Data repositories, and transaction management for database access."),
    q("JPA Repository", "annotation", "What does JpaRepository<T, ID> extend?",
      ["HttpServlet", "PagingAndSortingRepository and QueryByExampleExecutor among others", "RabbitTemplate", "JwtDecoder"],
      1, "JpaRepository adds flush, batch delete, and JPA-specific methods atop CrudRepository and PagingAndSortingRepository."),
    q("JPA Repository", "code", "How is this method implemented?",
      ["Manual SQL in XML only", "Spring Data derives query from method name findByLastName", "Compiler magic only", "Not supported"],
      1, "Query derivation parses findByLastName → WHERE lastName = ?. Custom queries use @Query JPQL or native SQL.",
      code='List<User> findByLastName(String lastName);'),
    q("JPA Repository", "annotation", "What does @Modifying on repository method indicate?",
      ["Read-only query", "UPDATE or DELETE query that changes data; often needs @Transactional", "Creates new table", "Feign call"],
      1, "@Modifying with @Query for UPDATE/DELETE requires clearAutomatically/flush and transactional context."),
    q("JPA Repository", "annotation", "What does @Query(value=\"...\", nativeQuery=true) do?",
      ["JPQL only", "Executes SQL directly against database", "Calls REST API", "Starts Eureka"],
      1, "nativeQuery=true runs vendor SQL. JPQL (default false) operates on entity names and fields."),
    q("Security Filter Chain", "theory", "What is Spring Security filter chain?",
      ["JUnit test chain", "Ordered servlet filters handling authn/authz before reaching DispatcherServlet", "Hibernate cache chain", "Git hooks"],
      1, "SecurityFilterChain beans configure filters for session, JWT, CSRF, authorization rules on each request."),
    q("Security Filter Chain", "theory", "Where does UsernamePasswordAuthenticationFilter sit conceptually?",
      ["After response sent", "Processes login form/basic auth and creates Authentication", "Replaces database", "Only in Angular"],
      1, "It attempts authentication from credentials and delegates to AuthenticationManager; success stores SecurityContext."),
    q("JWT Basics", "theory", "What are typical JWT sections?",
      ["Header, Payload, Signature", "Only password hash", "SQL, HTML, CSS", "Topic, Type, Question"],
      0, "JWT is header.algorithm + payload.claims + signature. Server verifies signature with secret/public key."),
    q("JWT Basics", "theory", "Should sensitive data be stored unencrypted in JWT payload?",
      ["Yes, always", "No—payload is Base64-encoded not encrypted; anyone can read claims", "JWT encrypts automatically", "Only in dev"],
      1, "JWTs are signed for integrity, not confidential by default. Use HTTPS and minimal claims; short expiry."),
    q("JWT Basics", "code", "What validates JWT on each request in stateless APIs?",
      ["@Entity", "OncePerRequestFilter or oauth2ResourceServer JWT decoder in filter chain", "@Scheduled", "Pageable"],
      1, "BearerTokenAuthenticationFilter or custom filter parses Authorization: Bearer <token>, validates signature and expiry.",
      code='// Filter extracts Bearer token, sets SecurityContext'),
    q("@PreAuthorize", "annotation", "What does @PreAuthorize(\"hasRole('ADMIN')\") require?",
      ["Nothing", "@EnableMethodSecurity and method intercepted by AOP", "Only @Entity", "RabbitMQ"],
      1, "Enable method security (@EnableMethodSecurity). SpEL in @PreAuthorize checks roles/authorities before method runs."),
    q("@PreAuthorize", "annotation", "Difference between hasRole('USER') and hasAuthority('ROLE_USER')?",
      ["Identical always", "hasRole adds ROLE_ prefix implicitly; hasAuthority matches exact string", "hasRole is for JWT only", "hasAuthority is deprecated"],
      1, "hasRole('USER') checks ROLE_USER authority. hasAuthority('ROLE_USER') is explicit—know your granted authority strings."),
    q("Spring Security", "theory", "What is Authentication vs Authorization?",
      ["Same thing", "Authentication proves identity; authorization decides access rights", "Authz is login form", "Authn is JWT only"],
      1, "Authentication (who are you) precedes authorization (what you may do)—roles, scopes, @PreAuthorize rules."),
    q("Eureka", "theory", "What is Netflix Eureka used for in microservices?",
      ["ORM", "Service registry: instances register and clients discover service locations", "Message broker", "CSS framework"],
      1, "Eureka server holds service instance metadata; clients heartbeat and fetch registry for load-balanced calls."),
    q("Eureka", "annotation", "Which annotation enables Eureka client registration?",
      ["@EnableEurekaClient or @EnableDiscoveryClient", "@EnableWebMvc", "@Entity", "@RabbitListener"],
      0, "Spring Cloud Netflix uses @EnableDiscoveryClient (preferred) to register with Eureka or other registries."),
    q("Feign", "theory", "What is OpenFeign in Spring Cloud?",
      ["Database driver", "Declarative REST client interface with annotations mapping to HTTP calls", "Unit test library", "View template"],
      1, "@FeignClient(name=\"order-service\") interface methods become HTTP requests with load balancing via discovery."),
    q("Feign", "annotation", "What does @FeignClient(\"inventory-service\") need at runtime?",
      ["Manual socket code", "Service discovery or explicit URL; Feign + LoadBalancer", "Only JPA", "Thymeleaf"],
      1, "Feign resolves service name through Eureka/Consul or url attribute. @EnableFeignClients scans interfaces."),
    q("Gateway", "theory", "What is Spring Cloud Gateway's primary role?",
      ["JPA provider", "API gateway: routing, filtering, cross-cutting concerns at edge", "Embedded Tomcat only", "Mockito runner"],
      1, "Gateway routes external requests to internal services, applying predicates/filters (auth, rate limit, rewrite paths)."),
    q("Gateway", "theory", "Gateway vs direct client-to-many-services?",
      ["Gateway always slower with no benefits", "Single entry point, centralized SSL, routing, and policies", "Clients must know all ports", "Gateway replaces database"],
      1, "Clients call gateway host; gateway load-balances to service instances hiding internal topology."),
    q("Resilience4j", "theory", "What does CircuitBreaker pattern prevent?",
      ["All HTTP traffic", "Cascading failures by failing fast when downstream is unhealthy", "SQL injection", "Compilation errors"],
      1, "After failure threshold, circuit opens and calls fail fast or use fallback until half-open retry probes recovery."),
    q("Resilience4j", "annotation", "Which annotation applies circuit breaker in Spring Boot 3 resilience4j?",
      ["@CircuitBreaker(name = \"orders\")", "@Entity", "@GetMapping only", "@PreDestroy"],
      0, "@CircuitBreaker on method with resilience4j.spring.boot3 integration—configure failure rate and wait duration in yaml."),
    q("Resilience4j", "theory", "What is Retry in Resilience4j?",
      ["Infinite loop always", "Configurable retries with backoff for transient failures", "Deletes database", "JWT refresh"],
      1, "@Retry attempts failed calls per policy—use only for idempotent operations to avoid duplicate side effects."),
    q("RabbitMQ", "theory", "What is RabbitMQ?",
      ["Relational database", "Message broker implementing AMQP for async messaging", "IDE plugin", "JWT library"],
      1, "Producers publish to exchanges; queues bind and consumers process messages asynchronously for decoupling."),
    q("RabbitMQ", "theory", "Exchange types in RabbitMQ include?",
      ["Only direct", "direct, fanout, topic, headers", "JWT, OAuth", "GET, POST"],
      1, "direct: routing key match; fanout: broadcast; topic: pattern routing; headers: header-based routing."),
    q("RabbitMQ", "annotation", "What does @RabbitListener do?",
      ["Creates JPA entity", "Marks method to consume messages from specified queue", "Enables Eureka", "Validates DTO"],
      1, "@RabbitListener(queues = \"order.created\") registers consumer container invoking method per message."),
    q("Spring Boot REST", "annotation", "What does application.properties spring.jpa.hibernate.ddl-auto=validate do?",
      ["Creates schema", "Checks schema matches entities without changing DB", "Deletes tables", "Disables JPA"],
      1, "validate fails startup if mappings mismatch schema—good with Flyway-managed production schema."),
    q("Spring Boot REST", "theory", "What is Actuator starter used for?",
      ["UI themes", "Production-ready endpoints: health, metrics, info", "ORM only", "Feign only"],
      1, "spring-boot-starter-actuator exposes /actuator/health and metrics integrated with Micrometer monitoring."),
    q("JPA Repository", "theory", "What is save() behavior for entity with null id?",
      ["Always update", "persist (insert) new entity; non-null id may merge/update", "Deletes row", "No-op"],
      1, "Spring Data save uses EntityManager persist/merge: new entity inserted, detached existing may merge."),
    q("Security Filter Chain", "code", "In SecurityFilterChain bean, authorizeHttpRequests().anyRequest().authenticated() means?",
      ["All requests public", "All requests need authenticated user unless other matchers permit", "Disables security", "Only static files secured"],
      1, "RequestMatchers can permitAll for /public/**; anyRequest().authenticated() requires logged-in/principal for rest.",
      code="http.authorizeHttpRequests(auth -> auth\n  .requestMatchers(\"/public/**\").permitAll()\n  .anyRequest().authenticated());"),
    q("JWT Basics", "theory", "Where should clients send JWT in HTTP?",
      ["Cookie only always", "Authorization: Bearer <token> header typically", "SQL WHERE clause", "Path variable"],
      1, "Bearer scheme in Authorization header is standard for stateless APIs. Secure cookies possible with caution (CSRF)."),
    q("Eureka", "theory", "What is self-preservation mode in Eureka?",
      ["Deletes all instances", "Protects registry when many heartbeats fail (network partition) to avoid mass eviction", "Encrypts JWT", "JPA feature"],
      1, "When too many instances miss renewals, Eureka assumes network issue and keeps stale entries temporarily."),
    q("Feign", "theory", "What is a Feign fallback or fallbackFactory?",
      ["JPA callback", "Provides default response when remote call fails (resilience)", "Hibernate cache", "Swagger tag"],
      1, "Fallback implements degraded behavior when circuit open or error—return cached data or friendly error."),
    q("Gateway", "code", "Route predicate Path=/api/orders/** routes to?",
      ["Random service", "Configured URI (e.g., lb://order-service) when path matches", "Database", "Rabbit queue"],
      1, "Spring Cloud Gateway RouteLocator defines predicates (Path, Header) and filters forwarding to downstream URIs."),
    q("Resilience4j", "theory", "Bulkhead pattern purpose?",
      ["Merge databases", "Limit concurrent calls to resource pool preventing thread exhaustion", "JWT signing", "HTML escaping"],
      1, "Bulkhead isolates thread pools so one slow dependency cannot starve entire application."),
    q("RabbitMQ", "theory", "Why use durable queue?",
      ["Faster always", "Queue survives broker restart (messages need persistent delivery mode too)", "No consumers needed", "Replaces transactions"],
      1, "durable=true on queue declaration survives restart; persistent messages survive with deliveryMode=2."),
    q("RabbitMQ", "theory", "Acknowledgment (ACK) in consuming means?",
      ["Ignore message", "Consumer confirms successful processing; broker removes message", "Publish only", "JWT verify"],
      1, "Manual ack after processing prevents message loss on consumer crash. auto ack risks loss if processing fails after ack."),
    q("@PreAuthorize", "code", "Who can call deleteOrder when annotation is @PreAuthorize(\"hasAuthority('ORDER_DELETE')\")?",
      ["Anyone anonymous", "Authenticated user with ORDER_DELETE authority", "All authenticated users", "Only Eureka server"],
      1, "Method security checks granted authorities on Authentication before invoking deleteOrder.",
      code='@PreAuthorize("hasAuthority(\'ORDER_DELETE\')")\npublic void deleteOrder(Long id) { ... }'),
    q("JPA Repository", "annotation", "What does @Transactional on service class do?",
      ["Starts HTTP server", "Defines transaction boundary; one persistence context per method typically", "Creates Feign client", "Opens Swagger"],
      1, "Spring @Transactional wraps method in DB transaction—commit on success, rollback on unchecked exceptions per propagation rules."),
    q("Spring Security", "theory", "CSRF protection in REST stateless JWT APIs is often?",
      ["Always required for Bearer token APIs", "Disabled when session-less and using tokens; still needed for cookie session apps", "Replaced by Eureka", "Same as circuit breaker"],
      1, "CSRF targets cookie-based sessions. Pure Bearer JWT APIs often disable CSRF; cookie auth must keep protection."),
    q("Gateway", "theory", "Load balancer prefix lb:// in Gateway URI means?",
      ["Local file path", "Use Spring Cloud LoadBalancer with service discovery", "LDAP bind", "Log backup"],
      1, "lb://order-service resolves instances from registry and load-balances requests reactively (WebFlux gateway)."),
]

PHASES = {
    "phase-06.json": PHASE_06,
    "phase-07.json": PHASE_07,
    "phase-08.json": PHASE_08,
    "phase-09.json": PHASE_09,
}


def main():
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    for filename, questions in PHASES.items():
        assert len(questions) == 42, f"{filename}: expected 42, got {len(questions)}"
        path = DATA_DIR / filename
        with path.open("w", encoding="utf-8") as f:
            json.dump({"questions": questions}, f, indent=2, ensure_ascii=False)
            f.write("\n")
        print(f"Wrote {path} ({len(questions)} questions)")


if __name__ == "__main__":
    main()
