#!/usr/bin/env python3
"""Generate phase-10 through phase-13 MCQ JSON files (42 questions each)."""
import json
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / "data"


def q(topic, qtype, question, options, answer, explanation, code=None):
    item = {
        "topic": topic,
        "type": qtype,
        "question": question,
        "options": options,
        "answer": answer,
        "explanation": explanation,
    }
    if code:
        item["code"] = code
    return item


PHASE_10 = {
    "id": "phase-10",
    "title": "Phase 10 — Web Basics & TypeScript Foundations",
    "questions": [
        q("HTML Semantics", "theory", "Which element should wrap the primary navigation links for a site?",
          ["<div class=\"nav\">", "<section>", "<nav>", "<header>"], 2,
          "<nav> is the semantic landmark for major navigation blocks."),
        q("HTML Semantics", "theory", "Where should the page's main unique content live?",
          ["<section>", "<main>", "<article>", "<div role=\"main\">"], 1,
          "<main> identifies the dominant content; avoid multiple per page unless hidden."),
        q("HTML Semantics", "theory", "Which element is most appropriate for a self-contained blog post preview?",
          ["<section>", "<article>", "<aside>", "<div>"], 1,
          "<article> represents independent, distributable content."),
        q("HTML Semantics", "theory", "What is the correct way to associate a <label> with an input when they are siblings?",
          ["Use name attribute on label", "Wrap input inside label only", "Set label for equal to input id", "Use aria-label on input"], 2,
          "for/id pairing improves accessibility and click target size."),
        q("HTML Forms", "theory", "Which input type enforces a numeric range in supporting browsers without JavaScript?",
          ["type=\"text\" pattern", "type=\"number\" with min/max", "type=\"range\" only", "type=\"tel\""], 1,
          "number inputs honor min, max, and step for native validation."),
        q("HTML Forms", "code", "What happens when this form is submitted?",
          ["GET to /save?x=1", "POST to /save with body x=1", "Nothing; method missing", "GET to current URL"], 0,
          "Forms default to method=\"get\"; without a method attribute the browser issues GET with query parameters.",
          code='<form action="/save"><input name="x" value="1"><button>Go</button></form>'),
        q("HTML Forms", "theory", "Which attribute makes a field required for native constraint validation?",
          ["validate", "mandatory", "required", "aria-required=\"true\""], 2,
          "required triggers built-in validation on submit."),
        q("HTML Forms", "theory", "What does autocomplete=\"off\" on a form primarily affect?",
          ["Server-side validation", "Browser suggestion of previously entered values", "Tab order", "CSRF tokens"], 1,
          "It hints browsers not to autofill; behavior varies by browser and field type."),
        q("HTML Forms", "theory", "For grouping related radio buttons, which is correct?",
          ["Same id on each input", "Same name on each input in the group", "Wrap in <fieldset type=\"radio\">", "Use type=\"checkbox\" with shared class"], 1,
          "Radios with the same name are mutually exclusive in a group."),
        q("CSS Flexbox", "theory", "Which property aligns flex items along the cross axis in a row flex container?",
          ["justify-content", "align-items", "align-content", "flex-direction"], 1,
          "align-items controls cross-axis alignment; justify-content is main axis."),
        q("CSS Flexbox", "code", "In a row flex container, which item will grow to fill leftover space?",
          [".a only", ".b only", ".b and .c equally", "All three"], 1,
          "flex-grow: 1 on .b allows it to absorb free space; .a has grow 0.",
          code=".a { flex: 0 1 auto; }\n.b { flex: 1 1 auto; }\n.c { flex: 0 0 100px; }"),
        q("CSS Flexbox", "theory", "What does justify-content: space-between do?",
          ["Adds equal margin around each item", "First at start, last at end, equal space between", "Centers the group", "Wraps items to new lines"], 1,
          "space-between distributes free space between items, not at edges."),
        q("CSS Flexbox", "theory", "Which value of flex-direction stacks items vertically with main axis top-to-bottom?",
          ["row-reverse", "column", "column-reverse", "block"], 1,
          "column sets main axis vertically."),
        q("CSS Grid", "theory", "Which property defines track sizes for columns?",
          ["grid-template-rows", "grid-auto-columns", "grid-template-columns", "grid-column-gap"], 2,
          "grid-template-columns explicitly sizes column tracks."),
        q("CSS Grid", "code", "How many columns does this create?\ngrid-template-columns: repeat(3, 1fr);",
          ["1", "2", "3", "Depends on item count"], 2,
          "repeat(3, 1fr) creates three equal fractional columns."),
        q("CSS Grid", "theory", "What does grid-area: 1 / 2 / 3 / 4 mean?",
          ["Row start 1, col start 2, row end 3, col end 4", "Column span 2, row span 3", "Grid line names", "Padding shorthand"], 0,
          "grid-area shorthand is row-start / col-start / row-end / col-end."),
        q("CSS Grid", "theory", "Which unit fr represents in CSS Grid?",
          ["Fixed rem fraction", "Fraction of free space in the grid container", "Frame rate", "Font-relative em"], 1,
          "fr distributes remaining space after non-flexible tracks."),
        q("Tailwind CSS", "theory", "What does the class `flex items-center justify-between` apply?",
          ["Block layout with centered text", "Flex container, cross-axis center, main-axis space-between", "Grid with centered items", "Inline flex only on children"], 1,
          "flex creates flex container; items-center and justify-between are flex utilities."),
        q("Tailwind CSS", "theory", "In Tailwind, how do you apply hover styles?",
          ["hover:flex", "hover:bg-blue-500", ":hover in @apply only", "data-hover attribute"], 1,
          "Variant prefixes like hover: precede utility names."),
        q("Tailwind CSS", "theory", "What is the purpose of `@tailwind base` in an input CSS file?",
          ["Import Google Fonts", "Inject Preflight/base styles from Tailwind", "Enable JIT only", "Define custom breakpoints"], 1,
          "@tailwind directives pull in Tailwind's layers (base, components, utilities)."),
        q("Tailwind CSS", "theory", "Which class adds padding on all sides at the `md` breakpoint and above?",
          ["md:p-4", "p-md-4", "p-4-md", "@md p-4"], 0,
          "Responsive variants prefix utilities: md:p-4."),
        q("JavaScript Basics", "theory", "What is the result of typeof null in JavaScript?",
          ["\"null\"", "\"undefined\"", "\"object\"", "\"number\""], 2,
          "typeof null is a long-standing quirk returning \"object\"."),
        q("JavaScript Basics", "code", "What is logged?\nconsole.log([1, 2] + [3, 4]);",
          ["[1,2,3,4]", "\"1,23,4\"", "7", "NaN"], 1,
          "Arrays coerce to strings via toString, producing \"1,2\" + \"3,4\"."),
        q("JavaScript Basics", "theory", "Which statement about `const` is true?",
          ["The binding cannot be reassigned; object properties may still change", "Values are deeply frozen", "const must be initialized at declaration in all engines", "const hoists like var"], 0,
          "const prevents rebinding, not mutation of object contents."),
        q("JavaScript Basics", "code", "What does this print?\nfor (var i = 0; i < 3; i++) {}\nconsole.log(i);",
          ["undefined", "0", "2", "3"], 3,
          "var is function-scoped; i remains 3 after the loop."),
        q("JavaScript Basics", "theory", "What does Array.prototype.map return?",
          ["The same array mutated", "A new array with transformed elements", "A single aggregated value", "An iterator"], 1,
          "map always returns a new array of the same length."),
        q("JavaScript Basics", "theory", "Which compares two values without type coercion?",
          ["==", "===", "Object.is only for objects", "compare()"], 1,
          "Strict equality === does not coerce types."),
        q("JavaScript Basics", "code", "What is the value of `a` after execution?\nlet a = 1;\nfunction f() { a = 2; }\nf();",
          ["1", "2", "undefined", "ReferenceError"], 1,
          "f closes over the outer binding and assigns 2."),
        q("JavaScript Basics", "theory", "What does the spread operator ...obj do when obj is a plain object in an object literal?",
          ["Clones deeply", "Copies enumerable own properties into the new object", "Spreads array indices only", "Throws if obj is frozen"], 1,
          "Object spread copies enumerable own properties (shallow)."),
        q("TypeScript", "theory", "What is the main purpose of TypeScript?",
          ["Replace JavaScript runtime", "Add static types checked at compile time", "Bundle CSS", "Provide a DOM polyfill"], 1,
          "TypeScript is a typed superset that compiles to JavaScript."),
        q("TypeScript", "code", "What error does TypeScript report?\nlet x: number = \"5\";",
          ["None; string is assignable", "Type 'string' is not assignable to type 'number'", "Runtime NaN", "Implicit any"], 1,
          "Explicit annotation number rejects string literal."),
        q("TypeScript", "theory", "What does the `interface` keyword create?",
          ["A runtime class", "A structural type shape for compile-time checking", "A sealed enum", "A namespace only"], 1,
          "Interfaces describe object shapes and are erased at compile time."),
        q("TypeScript", "theory", "How is `type Alias = { id: string }` different from an equivalent interface?",
          ["Interfaces cannot be extended", "type can express unions and primitives; interface is mainly for object shapes", "type exists at runtime", "interface enforces private fields"], 1,
          "type aliases are more flexible for unions/intersections; interfaces support declaration merging."),
        q("TypeScript", "code", "What is the inferred type of `t`?\nconst t = [1, \"a\"] as const;",
          ["(number | string)[]", "readonly [1, \"a\"]", "any[]", "[number, string] mutable"], 1,
          "as const makes the tuple readonly with literal types."),
        q("TypeScript", "theory", "What does `?` on a property mean in an interface?",
          ["Property must be null", "Property may be undefined (optional)", "Readonly property", "Deprecated"], 1,
          "Optional properties may be omitted or explicitly undefined."),
        q("TypeScript", "theory", "Which utility type makes all properties readonly?",
          ["Partial<T>", "Readonly<T>", "Pick<T,K>", "Record<K,V>"], 1,
          "Readonly<T> maps properties to readonly variants."),
        q("TypeScript", "theory", "What is `never` used for?",
          ["Any value including null", "Values that should never occur; exhaustiveness checks", "Empty object", "void return only"], 1,
          "never represents impossible types and helps exhaustive switch checking."),
        q("HTML Semantics", "theory", "Which attribute provides accessible name when visible label text is insufficient?",
          ["title only", "aria-labelledby or aria-label", "role=\"label\"", "alt on any element"], 1,
          "ARIA naming attributes expose accessible names to assistive tech."),
        q("CSS Flexbox", "theory", "What does flex-wrap: wrap enable?",
          ["Items shrink below min size", "Items move to additional flex lines when they overflow", "Reverses main axis", "Changes display to grid"], 1,
          "wrap allows multi-line flex layouts."),
        q("CSS Grid", "theory", "Which property gaps both rows and columns in modern CSS Grid?",
          ["gap", "grid-gap only (deprecated name)", "margin on items", "grid-spacing"], 0,
          "gap is the standard shorthand; grid-gap is legacy alias."),
        q("JavaScript Basics", "theory", "What does optional chaining `obj?.prop` return if obj is null?",
          ["Throws TypeError", "undefined", "null", "false"], 1,
          "Optional chaining short-circuits to undefined when base is nullish."),
        q("TypeScript", "theory", "What does `strictNullChecks` enable?",
          ["Disables null entirely", "null and undefined are distinct types not assignable to other types without narrowing", "Makes all fields optional", "Removes any"], 1,
          "With strictNullChecks, null/undefined must be handled explicitly."),
    ],
}

PHASE_11 = {
    "id": "phase-11",
    "title": "Phase 11 — Angular Components, Directives, Forms & Services",
    "questions": [
        q("Angular Components", "theory", "Which decorator marks a class as an Angular component?",
          ["@NgModule", "@Component", "@Injectable", "@Directive"], 1,
          "@Component defines selector, template, and styles."),
        q("Angular Components", "theory", "What is the purpose of `selector` in @Component?",
          ["CSS class name only", "Element/tag or attribute used to instantiate the component", "Route path", "Service token"], 1,
          "selector determines how the component is placed in templates."),
        q("Angular Components", "theory", "Which lifecycle hook runs after every change detection when @Input values change?",
          ["ngOnInit", "ngOnChanges", "ngAfterViewInit", "ngDoCheck"], 1,
          "ngOnChanges receives SimpleChanges when inputs update."),
        q("Angular Components", "code", "When is `ngOnInit` called relative to the first `ngOnChanges`?",
          ["Before first ngOnChanges", "After the first ngOnChanges (if inputs exist)", "Only on destroy", "Never with inputs"], 1,
          "ngOnInit runs once after the first ngOnChanges.",
          code="Component with @Input() id: string;"),
        q("Angular Lifecycle", "theory", "Which hook is best for cleaning up subscriptions?",
          ["ngOnInit", "ngOnDestroy", "ngAfterContentChecked", "constructor"], 1,
          "ngOnDestroy is the teardown hook."),
        q("Angular Lifecycle", "theory", "What does `ngAfterViewInit` indicate?",
          ["Component class constructed", "Child views and view queries initialized", "All HTTP complete", "Router activated"], 1,
          "View children are available after this hook."),
        q("Directives", "theory", "What is the difference between a component and a directive?",
          ["No difference", "Component has a template; directive augments an existing element", "Directive always has styles", "Component cannot use @Input"], 1,
          "Components are directives with their own view."),
        q("Directives", "code", "What renders with `*ngIf=\"false\"`?",
          ["Empty <p> in DOM", "No <p> in DOM (removed)", "<p style=\"display:none\">", "Comment node only always"], 1,
          "Structural *ngIf removes the template from DOM when false.",
          code='<p *ngIf="false">Hidden</p>'),
        q("Directives", "theory", "What does `*ngFor=\"let item of items; trackBy: trackId\"` optimize?",
          ["Network caching", "DOM reuse by stable identity when list changes", "Change detection disable", "Lazy loading modules"], 1,
          "trackBy helps Angular identify which items moved/changed."),
        q("Directives", "theory", "Which is structural directive syntax?",
          ["[ngClass]", "(click)", "*ngIf", "[hidden]"], 2,
          "Asterisk prefix denotes structural directives."),
        q("@Input / @Output", "theory", "How does a parent pass data to a child?",
          ["@Output binding", "Property binding to @Input on child", "providers array", "ViewChild only"], 1,
          "[prop]=\"value\" binds to child @Input."),
        q("@Input / @Output", "theory", "How does a child notify the parent of an event?",
          ["@Input emitter", "@Output EventEmitter with (event) binding in parent", "HttpClient", "ngOnChanges"], 1,
          "Child emits via EventEmitter; parent listens with (output)=\"handler()\"."),
        q("@Input / @Output", "code", "Parent template: `<child [count]=\"n\" (changed)=\"onChange($event)\">`. Child has @Output() changed. What is $event?",
          ["The child component instance", "Payload passed to emit()", "Always undefined", "MouseEvent"], 1,
          "$event in the parent is the value emitted by the child.",
          code="@Output() changed = new EventEmitter<number>();"),
        q("@Input / @Output", "theory", "What does `@Input() required: boolean` with `required: true` in Angular 16+ enforce?",
          ["Runtime throw if missing", "Compile-time check that parent must bind the input", "Automatic two-way binding", "Default value injection"], 1,
          "Required inputs are validated at compile time in strict templates."),
        q("Template-driven Forms", "theory", "Which module provides ngModel?",
          ["ReactiveFormsModule", "FormsModule", "HttpClientModule", "CommonModule only"], 1,
          "FormsModule exports NgModel for template-driven forms."),
        q("Template-driven Forms", "theory", "What does `[(ngModel)]=\"name\"` implement?",
          ["One-way to view only", "Banana in a box: property + event two-way binding", "Async pipe", "FormGroup binding"], 1,
          "[(ngModel)] combines [ngModel] and (ngModelChange)."),
        q("Template-driven Forms", "theory", "How do you show validation errors for a template-driven control?",
          ["form.invalid only", "#ref=\"ngModel\" and ref.invalid after submit/touch", "@Output from input", "Reactive validators only"], 1,
          "Export ngModel to a template ref to read errors."),
        q("Reactive Forms", "theory", "Which class builds a typed group of controls in code?",
          ["FormControl only", "FormBuilder.group / FormGroup", "NgForm", "HttpParams"], 1,
          "FormBuilder simplifies creating FormGroup hierarchies."),
        q("Reactive Forms", "code", "Which is valid reactive setup?",
          ["Template-driven only", "Requires FormsModule not ReactiveFormsModule", "Needs ReactiveFormsModule imported", "Uses @Input on FormControl"], 2,
          "ReactiveFormsModule provides form directives for [formGroup].",
          code="this.form = this.fb.group({ email: ['', Validators.required] });\n// In component with FormBuilder injected"),
        q("Reactive Forms", "theory", "What does `formControlName=\"email\"` require on the ancestor?",
          ["ngModel", "[formGroup] binding to a FormGroup", "routerLink", "*ngIf"], 1,
          "formControlName links to a named control inside parent FormGroup."),
        q("Reactive Forms", "theory", "How do you subscribe to value changes on a FormControl?",
          ["control.click()", "control.valueChanges", "NgZone.onStable", "@Output only"], 1,
          "valueChanges is an Observable emitting new values."),
        q("Services & DI", "theory", "Which decorator marks a class injectable by Angular DI?",
          ["@Component", "@Injectable", "@NgModule", "@Inject"], 1,
          "@Injectable registers the class with the injector."),
        q("Services & DI", "theory", "Where should app-wide singleton services be provided in standalone-era best practice?",
          ["In every component", "root injector via providedIn: 'root'", "Only in AppModule imports", "BrowserModule"], 1,
          "providedIn: 'root' registers a tree-shakable singleton."),
        q("Services & DI", "theory", "What does `inject(MyService)` do in a functional context (Angular 14+)?",
          ["Creates a new instance always", "Retrieves dependency from current injection context", "Mocks the service", "Registers a pipe"], 1,
          "inject() resolves tokens during construction/injection context."),
        q("Services & DI", "theory", "If ServiceA depends on ServiceB, who creates ServiceB?",
          ["Developer must call new ServiceB()", "Angular injector when A is requested", "HttpClient", "Router"], 1,
          "DI container resolves the dependency graph."),
        q("Pipes", "theory", "What does the `date` pipe do?",
          ["Parses JSON dates", "Formats a date value per locale/format string", "Converts to UTC timestamp", "Validates date input"], 1,
          "Built-in date pipe formats Date/string/number per pattern."),
        q("Pipes", "theory", "Pure pipes in Angular are called when?",
          ["Every mouse move", "When input reference changes or host change detection runs (pure default)", "Only manually", "On route change only"], 1,
          "Pure pipes memoize until input reference changes."),
        q("Pipes", "theory", "How do you declare a custom pipe?",
          ["@Injectable class Pipe", "@Pipe({ name: 'myPipe' }) class implementing PipeTransform", "@Directive only", "@Component with pipe: true"], 1,
          "Custom pipes use @Pipe and implement transform()."),
        q("Pipes", "code", "Template: `{{ price | currency:'USD' }}`. What appears (en-US)?",
          ["12.5", "$12.50", "USD 12.5", "12,50 USD"], 1,
          "currency pipe formats with symbol and decimals per locale.",
          code="price = 12.5"),
        q("Angular Components", "theory", "What is `encapsulation: ViewEncapsulation.Emulated` default behavior?",
          ["Global styles only", "Adds unique attributes to scope component CSS", "Disables all styles", "Shadow DOM mandatory"], 1,
          "Emulated encapsulation scopes styles via _ngcontent attributes."),
        q("Directives", "theory", "What does `[ngClass]=\"{ active: isActive }\"` do?",
          ["Adds static class active", "Toggles class active based on isActive", "Replaces all classes", "Binds style color"], 1,
          "Object syntax applies keys when values are truthy."),
        q("Directives", "theory", "Attribute directive `[hidden]` differs from `*ngIf` because?",
          ["hidden removes from DOM", "hidden toggles display but element stays in DOM", "ngIf is attribute only", "They are identical"], 1,
          "hidden uses CSS; *ngIf controls template presence."),
        q("Template-driven Forms", "theory", "What does `ngForm` represent?",
          ["Reactive FormGroup", "Top-level form directive with aggregate state", "Router form", "HTTP form encoder"], 1,
          "NgForm directive tracks controls registered via ngModel."),
        q("Reactive Forms", "theory", "What is `FormArray` used for?",
          ["Single checkbox", "Dynamic list of controls (e.g., repeating inputs)", "Route parameters", "HTTP headers"], 1,
          "FormArray holds an ordered list of AbstractControls."),
        q("@Input / @Output", "theory", "Can you rename an @Input for the template API?",
          ["No", "Yes with @Input('alias')", "Only in modules", "Only for outputs"], 1,
          "@Input('alias') exposes a different public property name."),
        q("Angular Lifecycle", "theory", "Which hook runs on every change detection cycle?",
          ["ngOnInit", "ngDoCheck", "ngOnDestroy", "constructor only"], 1,
          "ngDoCheck fires during every CD run; use carefully for performance."),
        q("Services & DI", "theory", "What is a common pitfall with services provided in a component?",
          ["Cannot inject HttpClient", "New instance per component instance (not singleton)", "Breaks routing", "Disables pipes"], 1,
          "Component providers create a child injector with new service per component."),
        q("Angular Components", "theory", "What does `standalone: true` on a component imply?",
          ["Cannot import anything", "Component can be bootstrapped/imported without declaring in NgModule", "No DI", "No templates"], 1,
          "Standalone components declare their own imports."),
        q("Reactive Forms", "theory", "How do you mark all controls touched to show errors?",
          ["form.reset()", "form.markAllAsTouched()", "NgForm.submit()", "Validators.compose"], 1,
          "markAllAsTouched propagates touched state."),
        q("Pipes", "theory", "Impure pipe `pure: false` is useful when?",
          ["Never; always avoid", "Transform depends on mutable state not passed as argument", "HTTP caching", "Routing guards"], 1,
          "Impure pipes run every CD cycle—use sparingly."),
        q("Directives", "theory", "Microsyntax `*ngFor=\"let x of list\"` desugars to?",
          ["Property binding only", "<ng-template ngFor let-x [ngForOf]=\"list\">", "JavaScript for loop", "Structural style binding"], 1,
          "Asterisk wraps content in ng-template with directive instance."),
        q("Template-driven Forms", "theory", "Difference between `novalidate` on form and Angular validators?",
          ["Same thing", "novalidate disables native browser UI; Angular validators still run", "Disables Angular validators", "Enables HTML4 only"], 1,
          "novalidate stops browser popup; Angular handles validation separately."),
    ],
}

PHASE_12 = {
    "id": "phase-12",
    "title": "Phase 12 — Angular Routing, HTTP, RxJS & Security",
    "questions": [
        q("Angular Routing", "theory", "Which module historically provided Router (still imported in many apps)?",
          ["HttpClientModule", "RouterModule.forRoot(routes)", "FormsModule", "BrowserAnimationsModule"], 1,
          "RouterModule.forRoot registers root routes and location strategy."),
        q("Angular Routing", "theory", "What does `{ path: '**', component: NotFoundComponent }` typically do?",
          ["Matches empty path", "Wildcard catch-all for unknown URLs", "Guards login", "Lazy loads module"], 1,
          "** is a wildcard route; order matters—usually last."),
        q("Angular Routing", "theory", "How do you navigate programmatically?",
          ["location.href only", "Router.navigate() or navigateByUrl()", "HttpClient.get", "NgZone.run"], 1,
          "Router service performs in-app navigation."),
        q("Angular Routing", "code", "Route: `{ path: 'users/:id', component: UserComponent }`. URL `/users/42`. How to read id?",
          ["route.data", "route.snapshot.paramMap.get('id')", "router.url string split", "@Input id only"], 1,
          "paramMap exposes route parameters like id.",
          code="// Inject ActivatedRoute"),
        q("Angular Routing", "theory", "What is lazy loading a feature module?",
          ["Loading all bundles upfront", "Loading module JS chunk on demand when route activates", "Caching HTTP", "Preloading images"], 1,
          "loadChildren triggers dynamic import of feature module."),
        q("NgModules", "theory", "What does `declarations` array in @NgModule contain?",
          ["Imported modules", "Components/directives/pipes belonging to this module", "Services only", "Routes"], 1,
          "declarations register components/directives/pipes owned by the module."),
        q("NgModules", "theory", "What is the difference between `imports` and `providers` in NgModule?",
          ["No difference", "imports: other modules; providers: DI tokens for this module scope", "imports: routes", "providers: templates"], 1,
          "imports compose module functionality; providers register services."),
        q("NgModules", "theory", "In standalone components, what replaces NgModule `imports`?",
          ["Nothing", "Component imports: [] array of other standalone/directives/modules", "providers only", "bootstrap array"], 1,
          "Standalone components list dependencies in their imports."),
        q("HttpClient", "theory", "What does HttpClient return by default for get<T>()?",
          ["Promise<T>", "Observable<T>", "T synchronously", "EventSource"], 1,
          "HttpClient methods return Observables."),
        q("HttpClient", "theory", "How do you send JSON body with POST?",
          ["Always automatic", "http.post(url, bodyObject) with default serializer", "Only FormData", "query params only"], 1,
          "HttpClient serializes plain objects to JSON with appropriate headers."),
        q("HttpClient", "theory", "What does `observe: 'response'` option return?",
          ["Body only", "Full HttpResponse including headers and status", "Blob always", "void"], 1,
          "observe response wraps body with status/headers."),
        q("HttpClient", "theory", "Where are HTTP interceptors registered?",
          ["In component styles", "HTTP_INTERCEPTORS multi provider", "RouterModule", "AppComponent template"], 1,
          "Multi-provider HTTP_INTERCEPTORS chain requests/responses."),
        q("RxJS", "theory", "What does Observable represent?",
          ["A single cached value", "A lazy stream of values over time", "A Promise replacement only", "DOM event list"], 1,
          "Observables push multiple values asynchronously."),
        q("RxJS", "theory", "What does `subscribe()` do?",
          ["Creates Observable", "Starts execution and listens for emissions/errors/complete", "Unsubscribes automatically always", "Converts to Promise always"], 1,
          "Subscription begins producer side effects for cold observables."),
        q("RxJS", "code", "What does pipe(map(x => x * 2)) do?",
          ["Subscribes immediately", "Transforms each emitted value", "Filters nulls only", "Caches last value"], 1,
          "map applies a projection function per emission.",
          code="source$.pipe(map(x => x * 2))"),
        q("RxJS", "theory", "When should you use `switchMap` vs `mergeMap`?",
          ["Identical", "switchMap cancels prior inner observable; mergeMap subscribes to all", "mergeMap cancels prior", "switchMap only for arrays"], 1,
          "switchMap is ideal for search/autocomplete; mergeMap for parallel ops."),
        q("RxJS", "theory", "What does `async` pipe do in templates?",
          ["Blocks UI", "Subscribes to Observable/Promise and marks view for check", "Converts Observable to array", "Caches HTTP"], 1,
          "async pipe manages subscribe/unsubscribe in templates."),
        q("RxJS", "theory", "What is the purpose of `takeUntil(destroy$)`?",
          ["Retry failed HTTP", "Complete subscription when destroy$ emits (avoid leaks)", "Debounce clicks", "Parse JSON"], 1,
          "Pattern ties stream lifetime to component destruction."),
        q("JWT & Interceptors", "theory", "What is a typical responsibility of an auth interceptor?",
          ["Compile TypeScript", "Attach Authorization: Bearer <token> header to outgoing requests", "Define routes", "Style components"], 1,
          "Interceptors mutate requests/responses in the chain."),
        q("JWT & Interceptors", "theory", "Where is a JWT usually stored in SPA debates—common secure-ish pattern?",
          ["localStorage (XSS risk) vs httpOnly cookie (CSRF considerations)", "URL query always", "sessionStorage only for server secrets", "IndexedDB for private keys"], 0,
          "Storage choice trades XSS vs CSRF; httpOnly cookies need CSRF protection."),
        q("JWT & Interceptors", "theory", "On 401 from API, an interceptor might?",
          ["Ignore", "Trigger logout or token refresh flow", "Delete the database", "Disable Angular CD"], 1,
          "Global handling can refresh token or redirect to login."),
        q("Route Guards", "theory", "What does `canActivate` guard control?",
          ["Whether a route may be activated", "Whether component can render CSS", "HTTP caching", "Form validity"], 0,
          "canActivate returns boolean/UrlTree/Observable to allow navigation."),
        q("Route Guards", "theory", "What does `canDeactivate` guard protect?",
          ["Login page", "Leaving a route with unsaved changes", "Lazy loading", "HTTP errors"], 1,
          "canDeactivate prompts before navigating away from a component."),
        q("Route Guards", "theory", "A guard returning `UrlTree` does what?",
          ["Throws error", "Redirects navigation to parsed route", "Cancels app", "Opens modal"], 1,
          "UrlTree redirect is built-in router behavior."),
        q("Angular Routing", "theory", "What is `routerLinkActive` used for?",
          ["Disable links", "Apply CSS class when link's route is active", "Prefetch lazy modules", "Validate forms"], 1,
          "routerLinkActive toggles classes for active route links."),
        q("Angular Routing", "theory", "Child routes are configured how?",
          ["Only in AppModule constructor", "children: [] under a parent route", "Guards array", "HttpInterceptor"], 1,
          "Nested routes render in parent router-outlet or named outlets."),
        q("HttpClient", "theory", "How to pass query params?",
          ["Only string concat", "HttpParams with get(url, { params })", "POST body", "@Input"], 1,
          "HttpParams builds encoded query strings safely."),
        q("RxJS", "theory", "What does `of(1,2,3)` create?",
          ["Promise", "Synchronous cold Observable emitting those values then complete", "Subject hot only", "BehaviorSubject"], 1,
          "of emits arguments synchronously then completes."),
        q("RxJS", "theory", "Difference between Subject and BehaviorSubject?",
          ["Subject stores last value for late subscribers", "BehaviorSubject requires initial value and replays latest to new subscribers", "Identical", "Subject is deprecated"], 1,
          "BehaviorSubject holds current value for new subscribers."),
        q("NgModules", "theory", "What does `exports` in NgModule do?",
          ["Export to npm", "Makes declared/imported artifacts available to importing modules", "HTTP export", "Build AOT"], 1,
          "exports expose components/directives/pipes to other modules."),
        q("HttpClient", "theory", "Error handling pattern for failed HTTP?",
          ["catchError in pipe", "try/catch around subscribe only works for sync", "ignore status", "router.navigate"], 0,
          "catchError operator transforms errors in Observable chain."),
        q("JWT & Interceptors", "theory", "JWT payload is typically?",
          ["Encrypted always", "Base64url-encoded JSON claims (signed, not encrypted by default)", "Binary protobuf", "Plain HTML"], 1,
          "JWTs are signed; payload is readable unless JWE used."),
        q("Route Guards", "theory", "`canMatch` guard (modern) differs from `canActivate` by?",
          ["No difference", "canMatch decides if route config matches before loading (e.g., role-based routes)", "Only for children", "Runs after destroy"], 1,
          "canMatch filters which route config applies."),
        q("Angular Routing", "theory", "Named router outlet syntax?",
          ["routerLink=\"/path(primary)\"", "routerLink with outlet name in array or routerLinkActive", "outlet=\"name\" on HttpClient", "*ngIf outlet"], 1,
          "Auxiliary routes use (outletName) in link arrays."),
        q("RxJS", "theory", "What does `debounceTime(300)` help with?",
          ["Login guard", "Wait for pause in emissions (e.g., search input)", "Retry HTTP 3 times", "Parse JWT"], 1,
          "debounceTime delays emissions until silence window."),
        q("HttpClient", "theory", "Testing HttpClient in Angular commonly uses?",
          ["Real network only", "HttpClientTestingModule and HttpTestingController", "RouterTestingModule", "No mocking possible"], 1,
          "HttpTestingController expects and flushes mock requests."),
        q("Angular Routing", "theory", "PreloadingStrategy purpose?",
          ["Block navigation", "Load lazy modules in background after initial navigation", "Delete cache", "Validate JWT"], 1,
          "Preload improves perceived performance for lazy routes."),
        q("RxJS", "theory", "Unsubscribing is important because?",
          ["Observables use no memory", "Leaked subscriptions keep handlers alive and may cause duplicate work", "Angular forbids subscribe", "AOT requires it"], 1,
          "Active subscriptions retain references and side effects."),
        q("Route Guards", "theory", "Functional guard `canActivate: [authGuard]` where authGuard is?",
          ["Class with @Injectable only", "CanActivateFn injected via inject() returning boolean/UrlTree", "Pipe", "Component method in template"], 1,
          "Modern functional guards use CanActivateFn."),
        q("JWT & Interceptors", "theory", "CSRF token pattern when using cookies for auth?",
          ["Not needed", "Send custom header/token that malicious sites cannot read cross-origin", "Disable HTTPS", "Use JWT in URL"], 1,
          "Double-submit cookie or custom header mitigates CSRF with cookies."),
        q("NgModules", "theory", "SharedModule anti-pattern to avoid?",
          ["Re-exporting CommonModule + many components creating huge import graph", "Providing services once", "Exporting RouterModule", "Using forChild"], 0,
          "Kitchen-sink SharedModule causes unnecessary bundle bloat."),
        q("HttpClient", "theory", "`reportProgress: true` enables?",
          ["Router events", "Upload/download progress events", "JWT refresh", "Change detection off"], 1,
          "Progress events useful for large file uploads."),
    ],
}

PHASE_13 = {
    "id": "phase-13",
    "title": "Phase 13 — Docker, Git & Application Architecture",
    "questions": [
        q("Docker Basics", "theory", "What is a Docker image?",
          ["A running process", "Read-only template with filesystem layers and metadata to create containers", "A volume mount", "A network bridge"], 1,
          "Images are immutable templates; containers are runtime instances."),
        q("Docker Basics", "theory", "What is a container?",
          ["Virtual machine with own kernel", "Isolated process(es) using image filesystem and namespaces/cgroups", "Dockerfile text file", "Registry account"], 1,
          "Containers share the host kernel but isolate process, FS, network."),
        q("Dockerfile", "theory", "What does `FROM node:20-alpine` specify?",
          ["Expose port", "Base image for subsequent instructions", "Run command", "Volume"], 1,
          "FROM sets the parent image layer stack."),
        q("Dockerfile", "theory", "Difference between `COPY` and `ADD`?",
          ["ADD can fetch URLs and auto-extract tar archives; COPY is preferred for simple file copy", "COPY downloads URLs", "ADD always faster", "Identical"], 0,
          "COPY is recommended unless ADD-specific features needed."),
        q("Dockerfile", "code", "What does this Dockerfile excerpt do?",
          ["Sets env only", "Sets working dir, copies manifests, installs deps in image layer", "Runs container", "Creates volume"], 1,
          "WORKDIR changes cwd; RUN executes during build.",
          code="WORKDIR /app\nCOPY package*.json ./\nRUN npm ci"),
        q("Dockerfile", "theory", "Why combine RUN instructions with `&&` in one layer?",
          ["Required by Docker", "Reduce image layers and size", "Enable GPU", "Mount secrets"], 1,
          "Fewer layers often mean smaller images."),
        q("Docker Volumes", "theory", "What problem do named volumes solve?",
          ["Faster CPU", "Persist data beyond container lifecycle", "Replace networks", "Build cache only"], 1,
          "Volumes store data outside container writable layer."),
        q("Docker Volumes", "theory", "Bind mount vs named volume?",
          ["Same", "Bind mounts host path directly; named volume managed by Docker", "Bind mount is read-only always", "Volume only in Dockerfile"], 1,
          "Bind mounts tie to specific host paths; volumes are portable."),
        q("Docker Networking", "theory", "Default network driver for containers on same host communicating by name?",
          ["host", "bridge (user-defined bridge enables DNS between containers)", "null", "overlay only"], 1,
          "Custom bridge networks provide automatic DNS between linked containers."),
        q("Docker Networking", "theory", "What does `docker run -p 8080:80` mean?",
          ["Container port 8080 to host 80", "Host port 8080 maps to container port 80", "Both UDP only", "Internal network only"], 1,
          "Format is host:container for port publishing."),
        q("Docker Networking", "theory", "`--network host` implies?",
          ["No network", "Container shares host network namespace (no port mapping isolation)", "Creates overlay swarm", "Deletes bridge"], 1,
          "host mode removes separate network namespace."),
        q("Docker Basics", "theory", "What is Docker Compose primarily for?",
          ["Replace Git", "Define multi-container apps in YAML and run with one command", "Compile Java", "Kubernetes replacement in prod always"], 1,
          "Compose orchestrates multiple services locally/dev."),
        q("Git Basics", "theory", "What does `git branch feature` create?",
          ["Deletes main", "A new branch pointer at current HEAD without switching", "Merges to main", "Tags a release"], 1,
          "branch creates ref; checkout -b also switches."),
        q("Git Basics", "theory", "What is `git merge feature` into main?",
          ["Rebases history linearly always", "Integrates feature commits into current branch, often creating merge commit", "Deletes feature", "Stashes changes"], 1,
          "merge combines histories of two branches."),
        q("Git Rebase", "theory", "What does interactive rebase `git rebase -i main` on a feature branch do?",
          ["Only fast-forward", "Replays commits on top of main, allowing squash/edit/reorder", "Pushes to remote automatically", "Creates tag"], 1,
          "Interactive rebase rewrites commits for cleaner history."),
        q("Git Rebase", "theory", "Golden rule of rebasing shared branches?",
          ["Always rebase main on team branches", "Avoid rebasing commits already pushed that others may have pulled", "Rebase instead of merge always", "Never use merge"], 1,
          "Rewriting public history forces collaborators to recover."),
        q("Git Stash", "theory", "What does `git stash push -m \"wip\"` do?",
          ["Commits to main", "Saves working directory/index changes temporarily and cleans tree", "Deletes untracked files always", "Creates branch"], 1,
          "stash shelves uncommitted work."),
        q("Git Stash", "theory", "How to reapply latest stash keeping it in stash list?",
          ["git stash drop", "git stash apply", "git stash clear", "git cherry-pick stash"], 1,
          "apply restores; pop applies and removes."),
        q("Git Workflow", "theory", "What is a fast-forward merge?",
          ["Always creates merge commit", "Main pointer moves forward when feature has no divergent commits", "Requires rebase", "Forbidden"], 1,
          "FF possible when target branch is direct ancestor."),
        q("Git Workflow", "theory", "`git pull` is equivalent to?",
          ["push + tag", "fetch + merge (or rebase if configured) into current branch", "stash only", "clone"], 1,
          "pull integrates remote changes after fetching."),
        q("Application Architecture", "theory", "In layered architecture, where should business rules live?",
          ["Presentation/UI layer", "Domain/service layer", "Database triggers only", "CDN"], 1,
          "Domain layer encapsulates business logic independent of UI/DB."),
        q("Application Architecture", "theory", "What is separation of concerns?",
          ["One giant class", "Dividing system into parts with distinct responsibilities and minimal coupling", "Microservices only", "No interfaces"], 1,
          "SoC improves maintainability and testability."),
        q("Application Architecture", "theory", "REST API statelessness means?",
          ["No database", "Each request contains all context server needs; server stores no client session state", "No HTTP", "Single endpoint"], 1,
          "Stateless servers scale horizontally; state in client/tokens/DB."),
        q("Application Architecture", "theory", "Monolith vs microservices trade-off?",
          ["Microservices always simpler locally", "Monolith simpler deploy/debug; microservices enable independent scaling/teams at operational cost", "Monolith cannot scale", "Identical ops cost"], 1,
          "Microservices add network, deployment, and observability complexity."),
        q("Application Architecture", "theory", "What is an API gateway role?",
          ["Database index", "Single entry routing, auth, rate limiting to backend services", "CSS bundler", "Git server"], 1,
          "Gateway centralizes cross-cutting edge concerns."),
        q("Docker Basics", "theory", "`.dockerignore` purpose?",
          ["Ignore Git branches", "Exclude files from build context like .gitignore", "Stop containers", "Network ACL"], 1,
          "Smaller context speeds build and avoids leaking secrets."),
        q("Dockerfile", "theory", "Multi-stage build benefit?",
          ["More layers always bigger", "Separate build and runtime images to shrink final image", "Requires two hosts", "Disables caching"], 1,
          "Final stage copies artifacts without build tools."),
        q("Docker Basics", "theory", "`docker exec -it container bash` does?",
          ["Build image", "Run interactive command inside running container", "Delete volume", "Create network"], 1,
          "exec attaches a process to an existing container."),
        q("Git Basics", "theory", "What does `git cherry-pick <commit>` do?",
          ["Deletes commit", "Applies specific commit's changes onto current branch", "Merges all branches", "Stashes"], 1,
          "cherry-pick copies one commit's patch."),
        q("Git Basics", "theory", "Merge conflict occurs when?",
          ["Empty repo", "Same lines changed differently on both branches being integrated", "Using Git LFS", "Fast-forward only"], 1,
          "Git cannot auto-merge divergent edits."),
        q("Application Architecture", "theory", "CQRS stands for?",
          ["Cache Query Remote Service", "Command Query Responsibility Segregation—separate read/write models", "Continuous Quality Review System", "Container Queue Routing"], 1,
          "CQRS splits commands from queries, often with different models."),
        q("Application Architecture", "theory", "Event-driven architecture uses?",
          ["Only synchronous REST", "Producers emit events consumers react to asynchronously", "No messaging", "Single thread only"], 1,
          "Loose coupling via events/message brokers."),
        q("Docker Networking", "theory", "Two containers on default bridge can talk by container name without user-defined network?",
          ["Yes always", "No—DNS by name works on user-defined bridge networks, not default bridge", "Only with Kubernetes", "Only host mode"], 1,
          "Legacy default bridge lacks automatic DNS between containers."),
        q("Docker Volumes", "theory", "`docker compose down -v`?",
          ["Stops only", "Stops and removes containers and named volumes declared in compose", "Builds images", "Pushes registry"], 1,
          "-v removes volumes defined in the compose file."),
        q("Git Rebase", "theory", "After rebase, pushing feature branch may require?",
          ["git push --force-with-lease (if branch was published)", "git pull --ff-only only", "git stash", "Nothing ever"], 0,
          "Rewritten history needs force-with-lease carefully."),
        q("Application Architecture", "theory", "Twelve-factor app config principle?",
          ["Hardcode in JAR", "Store config in environment, strict separation from code", "Use only XML", "Embed in Docker image only"], 1,
          "Config varies per deploy; env vars are standard."),
        q("Application Architecture", "theory", "Horizontal vs vertical scaling?",
          ["Vertical: more machines; Horizontal: bigger CPU", "Horizontal: add instances; Vertical: bigger single machine", "Same", "Only for monoliths"], 1,
          "Horizontal scale-out adds nodes; vertical scale-up adds resources."),
        q("Docker Basics", "theory", "Image layer caching during build invalidates when?",
          ["Never", "Instruction or prior copied file changes", "Container stops", "Git merge"], 1,
          "Changed Dockerfile line or input files bust cache from that step."),
        q("Git Workflow", "theory", "What is `origin` in Git?",
          ["Local branch only", "Default remote name for cloned repository", "Tag prefix", "Stash name"], 1,
          "origin typically points to the remote you cloned from."),
        q("Application Architecture", "theory", "Circuit breaker pattern prevents?",
          ["Git conflicts", "Cascading failures by failing fast when downstream is unhealthy", "SQL injection", "Docker layer bloat"], 1,
          "Stops hammering failing dependencies."),
        q("Dockerfile", "theory", "Why run app as non-root USER in container?",
          ["Faster builds", "Limit blast radius if container is compromised", "Required for bridge network", "Enables privileged mode"], 1,
          "Least privilege reduces impact of escapes/vulns."),
        q("Application Architecture", "theory", "Idempotent API operation means?",
          ["Always fails", "Multiple identical requests have same effect as one", "Encrypted only", "No logging"], 1,
          "Idempotency safe for retries (e.g., PUT with stable id)."),
    ],
}


def validate(phase):
    assert len(phase["questions"]) == 42, f"{phase['id']}: expected 42, got {len(phase['questions'])}"
    for i, qu in enumerate(phase["questions"]):
        assert len(qu["options"]) == 4, f"{phase['id']} Q{i+1}: need 4 options"
        assert 0 <= qu["answer"] <= 3, f"{phase['id']} Q{i+1}: answer out of range"


def main():
    DATA.mkdir(parents=True, exist_ok=True)
    for phase in (PHASE_10, PHASE_11, PHASE_12, PHASE_13):
        validate(phase)
        path = DATA / f"{phase['id']}.json"
        with path.open("w", encoding="utf-8") as f:
            json.dump(phase, f, indent=2, ensure_ascii=False)
            f.write("\n")
        print(f"Wrote {path} ({len(phase['questions'])} questions)")


if __name__ == "__main__":
    main()
