#!/usr/bin/env python3
"""Generate test-02.json and test-03.json (60 MCQs each)."""
import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data"


def mcq(category, topic, difficulty, qtype, question, options, answer, explanation, code=None):
    item = {
        "category": category,
        "topic": topic,
        "difficulty": difficulty,
        "type": qtype,
        "question": question,
        "options": options,
        "answer": answer,
        "explanation": explanation,
    }
    if code:
        item["code"] = code
    return item


# --- TEST 02: 28 medium, 32 hard (10 per category) ---
# Per-category mix: core-java/dbms/backend/angular 5M+5H; docker/sd 4M+6H

TEST_02_QUESTIONS = [
    # core-java (5 medium, 5 hard)
    mcq("core-java", "Collections", "medium", "code",
        "What is printed?",
        ["[1, 2]", "[2, 1]", "[1]", "UnsupportedOperationException at runtime"],
        0,
        "List.of creates an immutable list. stream().filter keeps 1 and 2; order is preserved.",
        'import java.util.*;\npublic class T {\n  public static void main(String[] a) {\n    var list = List.of(1, 2, 3);\n    System.out.println(list.stream().filter(n -> n < 3).toList());\n  }\n}'),
    mcq("core-java", "OOP", "medium", "theory",
        "Which statement about Java interfaces since Java 8 is correct?",
        ["Interfaces cannot have static methods", "Default methods allow adding methods without breaking implementers", "All interface methods are automatically synchronized", "Interfaces can extend only one class"],
        1,
        "Default and static methods in interfaces enable API evolution. Interfaces extend other interfaces, not classes."),
    mcq("core-java", "Exceptions", "medium", "code",
        "What happens when this runs?",
        ["Prints finally then rethrows ArithmeticException", "Prints caught then finally", "Prints only caught", "Compilation error"],
        1,
        "The catch runs for ArithmeticException, then finally always runs before the exception propagates.",
        'public class T {\n  public static void main(String[] a) {\n    try {\n      int x = 1 / 0;\n    } catch (ArithmeticException e) {\n      System.out.print("caught ");\n    } finally {\n      System.out.print("finally");\n    }\n  }\n}'),
    mcq("core-java", "Generics", "medium", "theory",
        "Why is List<Object> not a supertype of List<String> in Java generics?",
        ["Because String is final", "To preserve type safety at compile time (invariance)", "Because Object is abstract", "Only arrays behave that way, not lists"],
        1,
        "Generics are invariant: you cannot assign List<String> to List<Object> without unsafe casts."),
    mcq("core-java", "Streams", "medium", "code",
        "What does this print?",
        ["3", "6", "Optional[3]", "Compile error"],
        0,
        "reduce without identity returns OptionalInt; orElse(0) yields 3 for sum 1+2.",
        'import java.util.*;\npublic class T {\n  public static void main(String[] a) {\n    System.out.println(Arrays.asList(1, 2).stream().mapToInt(x -> x).reduce((x, y) -> x + y).orElse(0));\n  }\n}'),
    mcq("core-java", "Concurrency", "hard", "code",
        "How many lines can print \"done\" (best answer)?",
        ["Exactly once", "At most once", "Exactly twice", "Unbounded — race on unsynchronized check"],
        3,
        "Double-checked locking without volatile or proper publication can see stale values; also two threads may both pass if not synchronized — classic broken pattern without volatile.",
        'class T {\n  static boolean ready;\n  public static void main(String[] a) {\n    new Thread(() -> { if (ready) System.out.println("done"); }).start();\n    ready = true;\n  }\n}'),
    mcq("core-java", "JVM", "hard", "theory",
        "Which GC concern is most associated with frequent promotion of short-lived objects to the old generation?",
        ["Metaspace exhaustion only", "Increased full GC pauses due to old-gen filling", "Stack overflow", "Classloader leaks in PermGen on Java 8 only"],
        1,
        "Premature tenuring increases old-gen occupancy and can trigger costly full collections."),
    mcq("core-java", "Records", "hard", "theory",
        "What does the compiler synthesize for a public record R(int x)?",
        ["Only a private constructor", "Canonical constructor, accessors, equals, hashCode, toString", "Mutable setters for each component", "Automatic JPA @Entity mapping"],
        1,
        "Records are transparent carriers: canonical ctor, component accessors, and Object methods are generated."),
    mcq("core-java", "Modules", "hard", "practical",
        "A class in module A uses com.example.internal.Util from module B where Util is in a non-exported package. What is required?",
        ["Nothing if both are on the classpath", "B must export the package or use opens to A", "Rename Util to public", "Disable the module path"],
        1,
        "JPMS requires explicit exports (or qualified exports/opens) for cross-module access to non-exported packages."),
    mcq("core-java", "Memory Model", "hard", "theory",
        "What does volatile guarantee for a field?",
        ["Atomic read-modify-write for i++", "Visibility and ordering of reads/writes; not compound atomicity", "Locks the entire object", "Makes all fields of the class volatile"],
        1,
        "volatile ensures happens-before visibility; it does not make increment atomic."),

    # dbms (5 medium, 5 hard)
    mcq("dbms", "SQL Joins", "medium", "code",
        "Tables: Emp(id,name,dept_id), Dept(id,name). How many rows does this return if Emp has 3 rows (two share dept_id=1, one has dept_id NULL) and Dept has 2 rows?",
        ["3", "4", "5", "2"],
        1,
        "LEFT JOIN keeps all Emp rows; NULL dept_id still produces one row with NULL dept columns → 3 emp rows matched/NULL-padded.",
        "SELECT e.name, d.name FROM Emp e LEFT JOIN Dept d ON e.dept_id = d.id;"),
    mcq("dbms", "Normalization", "medium", "theory",
        "A relation has FDs: A→B, B→C, and key A. Highest normal form achieved?",
        ["1NF", "2NF", "3NF", "BCNF"],
        2,
        "No transitive dependency B→C on non-key (key is A) — satisfies 3NF; B is not a key so BCNF may fail if B→C with B not superkey."),
    mcq("dbms", "Indexing", "medium", "theory",
        "When is a non-clustered index on (last_name, first_name) most helpful?",
        ["Updates only primary key", "Queries filter/sort by last_name and optionally first_name", "Full table scans on numeric id", "Deleting all rows"],
        1,
        "Composite B-tree indexes support prefix searches on leading columns and ordered retrieval."),
    mcq("dbms", "Transactions", "medium", "theory",
        "Under READ COMMITTED, which phenomenon can still occur?",
        ["Dirty read", "Non-repeatable read", "Neither dirty nor non-repeatable", "Phantom-free always"],
        1,
        "READ COMMITTED prevents dirty reads; another transaction's commit can change rows you read again (non-repeatable read)."),
    mcq("dbms", "SQL", "medium", "code",
        "What does this return (single scalar subquery)?",
        ["Highest salary value", "Employee name with max salary", "Compile/ syntax error in standard SQL", "Two rows"],
        0,
        "Scalar subquery returns one value — MAX(salary). Name would need different query (e.g., ORDER BY LIMIT or window).",
        "SELECT (SELECT MAX(salary) FROM employees);"),
    mcq("dbms", "Window Functions", "hard", "code",
        "Employees: (Alice,100), (Bob,100), (Cara,90). What does RANK() OVER (ORDER BY salary DESC) assign to Alice and Bob?",
        ["Both 1", "Alice 1, Bob 2", "Both 2", "Alice 1, Bob 1 with next rank 3"],
        3,
        "RANK leaves gaps after ties: two rank-1 rows, next rank is 3."),
    mcq("dbms", "Isolation", "hard", "theory",
        "Which isolation level prevents phantoms in standard SQL semantics (with proper locking)?",
        ["READ UNCOMMITTED", "READ COMMITTED", "REPEATABLE READ (in some DBs with gap locks)", "Depends on engine; SERIALIZABLE prevents phantoms"],
        3,
        "SERIALIZABLE prevents phantoms; in MySQL InnoDB REPEATABLE READ often uses gap locks — answer emphasizes SERIALIZABLE as safe default."),
    mcq("dbms", "Execution Plans", "hard", "theory",
        "Nested loop join is typically preferred when:",
        ["Both inputs are huge unsorted heaps", "Outer is small and inner is indexed on join key", "No indexes exist", "Only CROSS JOIN is legal"],
        1,
        "Indexed nested loop: few outer rows, cheap index lookups on inner."),
    mcq("dbms", "Deadlock", "hard", "practical",
        "Transaction T1: UPDATE A then B. T2: UPDATE B then A. Both use row locks. Likely outcome?",
        ["Both always succeed", "Deadlock detected; one transaction aborted", "Dirty read", "Immediate cluster shutdown"],
        1,
        "Circular wait on rows A and B is classic deadlock; DBMS picks a victim."),
    mcq("dbms", "Stored Procedures", "hard", "theory",
        "Main advantage of parameterized queries over dynamic SQL string concatenation in procedures?",
        ["Faster network", "Prevents SQL injection and aids plan reuse", "Eliminates need for indexes", "Removes transactions"],
        1,
        "Bind parameters separate logic from data, mitigating injection and enabling plan cache reuse."),

    # backend (5 medium, 5 hard)
    mcq("backend", "Spring DI", "medium", "theory",
        "Why is constructor injection preferred over field injection in Spring?",
        ["Fields are faster", "Dependencies are explicit, immutable, and easier to unit test", "Constructor injection disables @Autowired", "Field injection is required for prototypes"],
        1,
        "Constructor injection makes required dependencies clear and supports final fields."),
    mcq("backend", "REST", "medium", "theory",
        "Which HTTP status best fits successful creation of a resource with a Location header?",
        ["200 OK", "201 Created", "204 No Content", "302 Found"],
        1,
        "201 Created indicates a new resource; Location identifies its URI."),
    mcq("backend", "JPA", "medium", "theory",
        "What does CascadeType.PERSIST on a parent→child association imply?",
        ["Deleting parent deletes children automatically", "persist() on parent cascades persist to new children", "Merges always cascade remove", "Lazy loading is disabled"],
        1,
        "PERSIST cascade propagates entityManager.persist from parent to associated children."),
    mcq("backend", "Spring Boot", "medium", "practical",
        "Where should externalized config for prod profile live by convention?",
        ["src/main/java/application.properties only", "application-prod.yml on classpath or env-specific config server", "pom.xml", "MANIFEST.MF"],
        1,
        "Profile-specific files (application-prod.yml) or config server supply environment overrides."),
    mcq("backend", "Testing", "medium", "theory",
        "@WebMvcTest slices which layer primarily?",
        ["Full database integration", "Controller layer with mocked collaborators", "Only repositories", "Docker containers"],
        1,
        "@WebMvcTest loads MVC controllers and mocks other beans — fast controller tests."),
    mcq("backend", "Transactions", "hard", "theory",
        "@Transactional(readOnly = true) on a service method primarily hints:",
        ["No SQLException possible", "Optimization: no flush of dirty state; some DBs route to replicas", "Automatic rollback on any RuntimeException always disabled", "Entity becomes detached immediately"],
        1,
        "readOnly skips unnecessary dirty checks/flushes and can enable read-replica routing."),
    mcq("backend", "Hibernate", "hard", "theory",
        "N+1 select problem in ORM is best mitigated by:",
        ["EAGER fetch everywhere", "JOIN FETCH / @EntityGraph / batch fetching for needed associations", "Disabling SQL logging", "Using Serializable isolation"],
        1,
        "Targeted fetch joins or batch size reduce per-entity lazy queries."),
    mcq("backend", "Security", "hard", "theory",
        "In Spring Security filter chain, where does UsernamePasswordAuthenticationFilter sit relative to authorization?",
        ["After authorization always", "Before SecurityContext is populated for authenticated requests", "Only in @Controller", "Replaces DispatcherServlet"],
        1,
        "Authentication filters run early to populate SecurityContext before authorization decisions."),
    mcq("backend", "Validation", "hard", "practical",
        "@Valid on a @RequestBody DTO fails validation. Default Spring MVC response without @ControllerAdvice?",
        ["200 with empty body", "400 Bad Request (MethodArgumentNotValidException) when configured", "500 always", "302 redirect"],
        1,
        "Binding/validation errors typically yield 400 unless customized via exception handler."),
    mcq("backend", "Caching", "hard", "theory",
        "@Cacheable unless condition prevents caching when:",
        ["Method returns null always", "SpEL condition evaluates false for that invocation", "Method is private", "Bean is prototype"],
        1,
        "unless/unless SpEL guards which results enter the cache."),

    # docker (4 medium, 6 hard)
    mcq("docker", "Images", "medium", "theory",
        "What does a Docker image layer represent?",
        ["A running process", "Filesystem diff applied on top of previous layers", "A Kubernetes pod", "A volume mount only"],
        1,
        "Images are layered FS diffs; containers add a writable layer on top."),
    mcq("docker", "CLI", "medium", "practical",
        "Which command removes stopped containers, unused networks, dangling images, and build cache (interactive)?",
        ["docker rm -f", "docker system prune", "docker kill all", "docker compose down --volumes always"],
        1,
        "docker system prune cleans unused Docker objects; add -a for unused images."),
    mcq("docker", "Compose", "medium", "theory",
        "In docker-compose.yml, depends_on ensures:",
        ["Service B is healthy before A starts (without healthcheck condition)", "Start order only; not application readiness by default", "Automatic load balancing", "TLS termination"],
        1,
        "depends_on orders container start; health-aware waits need depends_on with condition or wait scripts."),
    mcq("docker", "Volumes", "medium", "theory",
        "Bind mount vs named volume: which persists data managed by Docker and is portable across hosts (with driver)?",
        ["Bind mount to host path only", "Named volume", "tmpfs", "COPY in Dockerfile"],
        1,
        "Named volumes are managed under Docker storage drivers; bind mounts tie to host paths."),
    mcq("docker", "Networking", "hard", "theory",
        "Two containers on the same user-defined bridge network can communicate by:",
        ["Only localhost:8080 on host", "Container name DNS on the overlay/bridge network", "Must use --link (deprecated)", "Only with host network mode"],
        1,
        "Embedded DNS resolves service/container names to IPs on custom bridge networks."),
    mcq("docker", "Dockerfile", "hard", "practical",
        "Why combine RUN apt-get update && apt-get install in one Dockerfile RUN line?",
        ["Required by Kubernetes", "Reduces layer count and avoids stale apt cache in intermediate layers", "Makes image non-root", "Enables multi-arch only"],
        1,
        "Each RUN is a layer; combining commands avoids large intermediate layers with outdated indexes."),
    mcq("docker", "Security", "hard", "theory",
        "Running a container with --user 1000:1000 primarily:",
        ["Disables networking", "Avoids processes running as root inside the container", "Grants CAP_SYS_ADMIN", "Mounts /etc/shadow"],
        1,
        "Non-root UID/GID limits impact if the container is compromised."),
    mcq("docker", "Resources", "hard", "theory",
        "docker run --memory=512m limits:",
        ["Host RAM forever globally", "Container cgroup memory limit; OOM kill may occur inside container", "Java heap automatically", "Disk I/O only"],
        1,
        "cgroups enforce memory ceiling per container; JVM must still be tuned separately."),
    mcq("docker", "Multi-stage", "hard", "practical",
        "Multi-stage build benefit for Java apps?",
        ["More layers always", "Build with JDK in one stage, copy JAR to slim JRE runtime image", "Eliminates need for jar", "Runs tests in production image automatically"],
        1,
        "Builder stage compiles; final stage ships minimal runtime artifact."),
    mcq("docker", "Compose", "hard", "theory",
        "docker compose up -d --scale api=3 behind one published port without Swarm requires:",
        ["Nothing; default publish load-balances", "Reverse proxy or routing mesh; host port bind conflicts on multiple containers", "Only host network", "Kubernetes"],
        1,
        "Publishing same host port for scaled services conflicts; use proxy or don't publish per replica."),

    # angular (5 medium, 5 hard)
    mcq("angular", "Change Detection", "medium", "theory",
        "Default change detection strategy in Angular components is:",
        ["OnPush only", "CheckAlways (default)", "Manual only", "Zone-less always"],
        1,
        "Default is CheckAlways unless changeDetection: OnPush is set."),
    mcq("angular", "Routing", "medium", "theory",
        "What does Router navigate with { relativeTo: activatedRoute } enable?",
        ["Absolute URLs only", "Relative navigation from current route", "Bypassing guards", "SSR only"],
        1,
        "relativeTo anchors child/sibling routes relative to current ActivatedRoute."),
    mcq("angular", "Forms", "medium", "theory",
        "Reactive form control value is disabled. submitted value on form.value?",
        ["Includes disabled control", "Excludes disabled control by default in form.value", "Throws error", "Resets to null"],
        1,
        "form.value omits disabled controls; getRawValue() includes them."),
    mcq("angular", "HTTP", "medium", "practical",
        "HttpClient interceptors are useful for:",
        ["Replacing TypeScript compiler", "Attaching auth headers and central error handling", "Defining CSS themes", "Generating components"],
        1,
        "Interceptors chain requests/responses for cross-cutting concerns."),
    mcq("angular", "Dependency Injection", "medium", "theory",
        "providedIn: 'root' on an injectable means:",
        ["New instance per component always", "Singleton in root injector for app lifetime", "Only available in one module", "Provided only in tests"],
        1,
        "Tree-shakable root singleton unless overridden in a component/provider."),
    mcq("angular", "RxJS", "hard", "code",
        "What is emitted?",
        ["1 then complete", "1, 2 then complete", "Only 2", "Infinite 1s"],
        0,
        "of(1).pipe(concatMap(() => of(1))) emits 1 once then completes; concatMap subscribes to inner sequentially.",
        "import { of, concatMap } from 'rxjs';\nof(1).pipe(concatMap(() => of(1))).subscribe(console.log);"),
    mcq("angular", "Signals", "hard", "theory",
        "computed(() => expr) signal differs from effect(() => expr) because:",
        ["computed is async only", "computed derives cached value; effect runs side effects", "effect returns a Signal", "They are identical"],
        1,
        "computed is pure derivation; effect schedules side effects when dependencies change."),
    mcq("angular", "Performance", "hard", "theory",
        "OnPush component updates when:",
        ["Never", "Input reference changes, events from template, async pipe emission, markForCheck", "Only zone runs globally", "Only @Output fires"],
        1,
        "OnPush checks on new inputs, DOM events, observables via async pipe, or explicit markForCheck."),
    mcq("angular", "Guards", "hard", "practical",
        "CanActivate returns UrlTree. What happens?",
        ["Guard ignored", "Router cancels navigation and redirects per UrlTree", "Component still loads", "HttpClient retries"],
        1,
        "UrlTree redirect is the modern pattern for conditional navigation denial."),
    mcq("angular", "Standalone", "hard", "theory",
        "Standalone component imports array replaces need for:",
        ["NgModule declaring that component in many cases", "TypeScript", "package.json", "zone.js"],
        0,
        "Standalone components import dependencies directly, reducing NgModule ceremony."),

    # software-development (4 medium, 6 hard)
    mcq("software-development", "Git", "medium", "theory",
        "git rebase main on a feature branch rewrites commits to:",
        ["Delete main", "Replay feature commits on top of latest main tip", "Merge main with merge commit only", "Remove all history"],
        1,
        "Rebase reapplies commits onto a new base for linear history."),
    mcq("software-development", "SOLID", "medium", "theory",
        "Open/Closed Principle encourages:",
        ["Classes open for modification everywhere", "Extension without modifying existing tested code", "One giant class", "No interfaces"],
        1,
        "Open for extension, closed for modification — use abstractions/strategies."),
    mcq("software-development", "Agile", "medium", "theory",
        "Definition of Done in Scrum typically applies to:",
        ["Only product backlog items in sprint", "Increment — potentially shippable work meeting team standards", "Daily standup notes", "Retrospective actions only"],
        1,
        "DoD is shared quality bar for work considered complete in the increment."),
    mcq("software-development", "Code Review", "medium", "practical",
        "Effective review comment focuses on:",
        ["Personal style only", "Correctness, design, security, and maintainability with specifics", "Blame author", "Rewriting entire PR silently"],
        1,
        "Actionable, respectful feedback on behavior and design beats nitpicks."),
    mcq("software-development", "Microservices", "hard", "theory",
        "Saga pattern compensating transactions address:",
        ["ACID across distributed DBs without coordination", "Long-lived distributed transactions via local txs + compensating steps", "UI routing", "Docker layer caching"],
        1,
        "Sagas use choreography/orchestration with compensations instead of 2PC."),
    mcq("software-development", "CAP", "hard", "theory",
        "During a network partition, CP system choice implies:",
        ["Always available writes", "May reject operations to preserve consistency", "No replication", "No leaders"],
        1,
        "CP sacrifices availability under partition to keep consistent reads/writes."),
    mcq("software-development", "API Design", "hard", "theory",
        "Idempotent HTTP method for PUT replacing a resource at a URI:",
        ["First call creates, repeats same state (same idempotent effect)", "Each call creates new resource always", "Cannot update", "Only DELETE is idempotent"],
        0,
        "PUT at a URI is idempotent: repeated identical PUT leaves resource in same state."),
    mcq("software-development", "Observability", "hard", "theory",
        "RED metrics for microservices stand for:",
        ["Random, Error, Debug", "Rate, Errors, Duration", "Redis, Elastic, Docker", "Read, Execute, Delete"],
        1,
        "Rate (requests), Errors, Duration — common service monitoring triad."),
    mcq("software-development", "Twelve-Factor", "hard", "theory",
        "Config in twelve-factor apps should be:",
        ["Hard-coded in JAR", "Stored in environment / config service, not source", "Only in XML", "Compiled into native image only"],
        1,
        "III. Config — environment-specific settings via env vars/secrets stores."),
    mcq("software-development", "Coupling", "hard", "theory",
        "Strangler fig pattern helps migrate monolith by:",
        ["Big-bang rewrite", "Incrementally routing functionality to new services around legacy", "Deleting database", "Removing tests"],
        1,
        "Gradually replace edges of monolith with new implementation behind facade/router."),
]

# --- TEST 03: 12 medium, 48 hard (2 medium + 8 hard per category) ---

TEST_03_QUESTIONS = [
    # core-java (2M, 8H)
    mcq("core-java", "String Pool", "medium", "code",
        "What is printed (Java 17+ with compact strings)?",
        ["true true", "true false", "false false", "Compile error"],
        1,
        "s2 is interned literal pool reference; s3 is new String(s1) — different object, s1==s2 true, s1==s3 false.",
        'public class T {\n  public static void main(String[] a) {\n    String s1 = "hi";\n    String s2 = "hi";\n    String s3 = new String(s1);\n    System.out.println(s1 == s2);\n    System.out.println(s1 == s3);\n  }\n}'),
    mcq("core-java", "Optional", "medium", "code",
        "Output?",
        ["5", "0", "Optional.empty", "NoSuchElementException"],
        0,
        "map on present Optional chains; orElse only if empty — value is 5.",
        'import java.util.*;\npublic class T {\n  public static void main(String[] a) {\n    System.out.println(Optional.of(5).map(n -> n).orElse(0));\n  }\n}'),
    mcq("core-java", "Streams", "hard", "code",
        "Terminal operation used twice on same stream — result?",
        ["Second collect returns same list", "IllegalStateException: stream already operated upon", "Empty list", "Undefined but compiles"],
        1,
        "Streams are single-use; second terminal throws IllegalStateException."),
    mcq("core-java", "CompletableFuture", "hard", "theory",
        "thenApplyAsync vs thenApply on default executor — key difference?",
        ["thenApply always blocks calling thread", "thenApplyAsync runs callback on ForkJoinPool/common pool (unless executor supplied)", "Identical", "thenApplyAsync is deprecated"],
        1,
        "Async variant schedules on executor; sync runs on completing thread (or caller)."),
    mcq("core-java", "Class Loading", "hard", "theory",
        "Parent delegation model loads class com.app.Foo. Order?",
        ["App loader first always", "Bootstrap → Platform → App loader if not found upward", "Random loader", "Only bootstrap"],
        1,
        "Loaders delegate up before defining; prevents core class spoofing."),
    mcq("core-java", "Varhandles", "hard", "theory",
        "Compared to synchronized, VarHandle compareAndSet offers:",
        ["Always slower", "Lock-free atomic conditional update on fields/arrays", "Only for static fields", "GC root pinning"],
        1,
        "VarHandles expose CAS and ordered access for low-level concurrency."),
    mcq("core-java", "Sealed Classes", "hard", "theory",
        "sealed class Shape permits Circle, Square. Class Triangle extends Shape —",
        ["Allowed if public", "Compile error unless Triangle is permitted", "Runtime error only", "Allowed in same file only always"],
        1,
        "Subclasses must be explicitly permitted or be in same package/module as sealed class."),
    mcq("core-java", "Garbage Collection", "hard", "theory",
        "G1 GC region evacuation failure often indicates:",
        ["Too small heap or humongous objects fragmentation pressure", "Too many interfaces", "Missing main method", "Only classloader leak"],
        0,
        "Evacuation failure triggers Full GC — often heap pressure or humongous allocations."),
    mcq("core-java", "ForkJoin", "hard", "code",
        "RecursiveTask fork/join — common pitfall?",
        ["Too few tasks", "Splitting work too fine causes overhead exceeding benefit", "Cannot use thread pools", "Always single-threaded"],
        1,
        "Excessive decomposition thrashes work-stealing; balance threshold matters."),
    mcq("core-java", "Reflection", "hard", "practical",
        "setAccessible(true) on private field in Java 9+ module without opens:",
        ["Always allowed", "InaccessibleObjectException unless module opens package", "Only in applets", "Ignored silently"],
        1,
        "Strong encapsulation blocks illegal reflective access across module boundaries."),

    # dbms (2M, 8H)
    mcq("dbms", "GROUP BY", "medium", "code",
        "Valid standard SQL?",
        ["SELECT dept, MAX(sal) FROM emp", "SELECT dept, name, MAX(sal) FROM emp GROUP BY dept", "SELECT dept, MAX(sal) FROM emp GROUP BY dept, name", "SELECT MAX(sal) FROM emp GROUP BY dept HAVING COUNT(*) > 1"],
        0,
        "Non-aggregated columns must appear in GROUP BY; A is valid; B invalid (name not grouped)."),
    mcq("dbms", "NULL", "medium", "theory",
        "WHERE col NOT IN (SELECT ...) when subquery returns NULL row:",
        ["Rows match normally", "Unknown/false behavior — NOT IN with NULL in set filters unpredictably", "All rows returned", "Syntax error"],
        1,
        "NULL in NOT IN subquery yields UNKNOWN; row excluded — use NOT EXISTS instead."),
    mcq("dbms", "CTEs", "hard", "code",
        "Recursive CTE missing termination condition causes:",
        ["Faster query", "Runaway recursion until DB limit/error", "Automatic LIMIT 100", "Index-only scan"],
        1,
        "Recursive member must converge; otherwise max recursion exceeded."),
    mcq("dbms", "Locking", "hard", "theory",
        "SELECT ... FOR UPDATE SKIP LOCKED is used for:",
        ["Serializing all readers", "Work-queue patterns — skip rows locked by others", "DDL migrations", "Backup only"],
        1,
        "SKIP LOCKED lets concurrent workers grab available rows without blocking."),
    mcq("dbms", "MVCC", "hard", "theory",
        "PostgreSQL MVCC old row versions are cleaned by:",
        ["Immediate delete on UPDATE", "VACUUM (autovacuum) reclaiming dead tuples", "DROP TABLE", "Only restart"],
        1,
        "Updates leave dead tuples until vacuum reclaims space."),
    mcq("dbms", "Indexes", "hard", "theory",
        "Covering index (index-only scan) requires:",
        ["Clustered index only", "All selected columns present in index including INCLUDE columns", "Full table scan", "No WHERE clause"],
        1,
        "Planner can satisfy query from index without heap fetch when visibility map allows."),
    mcq("dbms", "Replication", "hard", "theory",
        "Async replication lag means:",
        ["Standby has committed transactions not yet applied", "Primary cannot write", "No failover possible", "Synchronous commits on primary"],
        0,
        "Replica may trail primary; RPO/RTO implications for failover."),
    mcq("dbms", "Query Optimization", "hard", "theory",
        "Correlated subquery in SELECT list executed:",
        ["Once per database", "Once per outer row typically", "Never", "Only at commit"],
        1,
        "Correlation re-evaluates subquery for each outer row unless decorrelated."),
    mcq("dbms", "Constraints", "hard", "practical",
        "DEFERRABLE INITIALLY DEFERRED foreign key allows:",
        ["Violations forever", "Checking FK at COMMIT within transaction", "No transactions", "Only on temp tables"],
        1,
        "Constraint checked at end of statement or transaction per definition."),
    mcq("dbms", "Partitioning", "hard", "theory",
        "Partition pruning helps when:",
        ["Query filters on partition key", "Always without WHERE", "Only for views", "Using CROSS JOIN"],
        0,
        "Optimizer scans relevant partitions only when predicates match partition key."),

    # backend (2M, 8H)
    mcq("backend", "Spring Security", "medium", "theory",
        "CSRF protection in Spring Security for state-changing browser forms typically uses:",
        ["JWT in header only", "Synchronizer token pattern / cookie+header for SPA", "No protection needed", "Basic auth only"],
        1,
        "CSRF tokens or cookie-based patterns protect session cookie clients; APIs often disable with stateless JWT."),
    mcq("backend", "Spring Boot", "medium", "theory",
        "@ConditionalOnProperty activates bean when:",
        ["Property matches specified name/value in Environment", "Application is web", "Always", "JUnit runs"],
        0,
        "Conditional annotations gate auto-config based on classpath and properties."),
    mcq("backend", "OAuth2", "hard", "theory",
        "Resource server validates:",
        ["Client secret only", "Access token (JWT or opaque introspection) on each request", "Refresh token on every API call", "Session cookie from browser only always"],
        1,
        "Bearer access token proves authorization for resource access."),
    mcq("backend", "Spring Security", "hard", "theory",
        "Method-level @PreAuthorize uses:",
        ["Servlet filter only", "AOP proxy with SecurityExpressionRoot evaluating SpEL", "JdbcTemplate", "Hibernate interceptor"],
        1,
        "@EnableMethodSecurity wires AOP advisors for pre/post authorization."),
    mcq("backend", "JPA", "hard", "theory",
        "Persistence context flush before query causes:",
        ["Lost updates always", "Pending changes may be written to DB so query sees consistent state", "Detached entities merge automatically", "No SQL"],
        1,
        "Auto-flush synchronizes persistence context before certain queries."),
    mcq("backend", "Reactive", "hard", "theory",
        "WebFlux with bounded elastic scheduler is suited for:",
        ["Blocking JDBC on elastic threads, not on event loop", "All blocking on netty event loop", "Replacing HTTP", "Only @RestController MVC"],
        0,
        "Never block event loop; offload blocking work to boundedElastic."),
    mcq("backend", "Circuit Breaker", "hard", "theory",
        "Resilience4j circuit OPEN state:",
        ["Passes all calls through", "Fails fast without calling downstream", "Half-open forever", "Only for databases"],
        1,
        "OPEN rejects calls immediately until probe transitions to half-open."),
    mcq("backend", "Kafka", "hard", "theory",
        "Consumer group rebalancing occurs when:",
        ["Members join/leave or partitions change", "Every message", "Only on broker restart never", "Producer sends"],
        0,
        "Group coordinator redistributes partition assignments on membership changes."),
    mcq("backend", "API Versioning", "hard", "practical",
        "Header-based versioning (Accept: application/vnd.company.v2+json) advantage:",
        ["Breaks caching always", "URI stays stable; clients negotiate version", "Requires new hostname", "Disables content negotiation"],
        1,
        "Media type versioning keeps URLs clean while supporting multiple representations."),
    mcq("backend", "Actuator", "hard", "theory",
        "Exposing /actuator/env in production without security:",
        ["Recommended", "Leaks configuration/secrets — must secure or disable sensitive endpoints", "Required for health", "Replaces Vault"],
        1,
        "Actuator endpoints can expose sensitive data; lock down with Spring Security."),

    # docker (2M, 8H)
    mcq("docker", "Networks", "medium", "theory",
        "host network mode means container:",
        ["Gets isolated IP only", "Shares host network namespace (no separate docker0 IP)", "Cannot bind ports", "Uses only DNS"],
        1,
        "host mode removes network isolation — container uses host interfaces."),
    mcq("docker", "Inspect", "medium", "practical",
        "Find container IP on custom bridge:",
        ["docker logs", "docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <id>", "docker rm", "docker commit"],
        1,
        "inspect shows network attachments and IPs per network."),
    mcq("docker", "Overlay", "hard", "theory",
        "Docker overlay network driver primarily used for:",
        ["Single-host bridge only", "Multi-host container networking (Swarm/K8s CNI integrations)", "Static linking", "Replacing DNS"],
        1,
        "overlay encapsulates cross-node container traffic in distributed setups."),
    mcq("docker", "iptables", "hard", "theory",
        "Published port -p 8080:80 creates DNAT via:",
        ["Manual ssh only", "docker-proxy/iptables rules forwarding host:8080 to container:80", "Changes image CMD", "Removes bridge"],
        1,
        "Port publishing sets up forwarding from host to container IP:port."),
    mcq("docker", "Healthcheck", "hard", "practical",
        "HEALTHCHECK failing status causes:",
        ["Immediate image delete", "Container marked unhealthy; orchestrators may restart", "Network removal only", "Volume wipe"],
        1,
        "Unhealthy state signals supervisors (Swarm/K8s via probes) to act."),
    mcq("docker", "BuildKit", "hard", "theory",
        "BuildKit cache mount RUN --mount=type=cache benefits:",
        ["Slower builds", "Persists package manager caches between builds without bloating final image", "Only for Windows", "Disables multi-stage"],
        1,
        "Cache mounts speed installs while keeping final image slim."),
    mcq("docker", "seccomp", "hard", "theory",
        "Default Docker seccomp profile:",
        ["Allows all syscalls", "Blocks dangerous syscalls; can be customized", "Only for privileged containers", "Replaces AppArmor always"],
        1,
        "Seccomp filters syscall surface; custom profiles tighten further."),
    mcq("docker", "Registry", "hard", "practical",
        "Image digest pull (@sha256:...) ensures:",
        ["Latest tag always", "Immutable content-addressed image regardless of tag movement", "Smaller download", "No layers"],
        1,
        "Digest pins exact manifest for reproducible deploys."),
    mcq("docker", "Compose", "hard", "theory",
        "Compose profiles allow:",
        ["Random container names", "Activating optional services with --profile debug", "Deleting volumes always", "Only one service"],
        1,
        "Profiles enable conditional service groups in one compose file."),
    mcq("docker", "cgroups v2", "hard", "theory",
        "With cgroups v2, memory and CPU limits are:",
        ["Ignored", "Unified hierarchy controlled via cgroupfs/systemd delegation", "Only for VMs", "Set in Dockerfile ENV"],
        1,
        "Modern Docker uses cgroup v2 unified tree for resource limits."),

    # angular (2M, 8H)
    mcq("angular", "RxJS", "medium", "code",
        "How many values logged?",
        ["0", "1", "2", "Infinite"],
        1,
        "of(3) emits once; map doubles to 6; take(1) forwards that single value then completes.",
        "import { of } from 'rxjs';\nimport { map, take } from 'rxjs/operators';\nof(3).pipe(map(x => x * 2), take(1)).subscribe(console.log);"),
    mcq("angular", "Templates", "medium", "theory",
        "*ngIf=\"user; else guest\" — else block template requires:",
        ["ng-template #guest", "div #guest only", "@Component guest", "router-outlet"],
        0,
        "Else reference points to ng-template with matching local ref."),
    mcq("angular", "RxJS", "hard", "code",
        "switchMap vs mergeMap for HTTP autocomplete — prefer switchMap because:",
        ["It runs all requests in parallel always", "It cancels prior inner observable when new search term arrives", "It buffers all", "It is slower always"],
        1,
        "switchMap unsubscribes previous inner subscription on new outer emission — avoids race."),
    mcq("angular", "Change Detection", "hard", "theory",
        "async pipe in template primarily:",
        ["Blocks UI thread", "Subscribes and marks branch for check on emit; auto-unsubscribes", "Converts to Promise only", "Disables OnPush"],
        1,
        "async pipe manages subscription lifecycle and triggers CD for OnPush."),
    mcq("angular", "NgZone", "hard", "theory",
        "runOutsideAngular used when:",
        ["You need extra CD cycles", "Heavy work should not trigger global change detection each tick", "Routing fails", "Forms invalid"],
        1,
        "Run frequent non-UI work outside zone; re-enter when updating bindings."),
    mcq("angular", "ControlValueAccessor", "hard", "theory",
        "Custom form control integrates with reactive forms via:",
        ["@Input only", "Implementing ControlValueAccessor and providing NG_VALUE_ACCESSOR", "HttpClient", "RouterModule"],
        1,
        "CVA bridges custom UI widgets to Angular forms API."),
    mcq("angular", "SSR", "hard", "theory",
        "Angular Universal transferState avoids:",
        ["Client bootstrap", "Re-fetching same API data on client after SSR HTML", "Using HTTP", "Components"],
        1,
        "Serialized state hydrates client without duplicate HTTP for initial data."),
    mcq("angular", "Signals", "hard", "theory",
        "effect() cannot write to signals that are read in the same effect without:",
        ["Nothing", "Potential infinite loop — use untracked() or redesign", "Always allowed", "Only in NgModule"],
        1,
        "Writing to dependencies inside same effect retriggers — use untracked for benign writes."),
    mcq("angular", "Router", "hard", "practical",
        "runGuardsAndResolvers: 'paramsOrQueryParamsChange' re-runs resolvers when:",
        ["Never", "Route params or query params change on same route config", "Only module loads", "Only on first navigation"],
        1,
        "Fine-grained control for resolver refresh without component destroy."),
    mcq("angular", "Bundle", "hard", "theory",
        "Lazy-loaded route chunk loading failure (network) — best UX:",
        ["Silent fail", "Retry or error route; router error handler / custom preloading strategy", "Disable lazy loading always", "Delete service worker"],
        1,
        "Handle failed dynamic import with retry feedback or fallback navigation."),

    # software-development (2M, 8H)
    mcq("software-development", "Design Patterns", "medium", "theory",
        "Strategy pattern intent:",
        ["One instance globally", "Encapsulate interchangeable algorithms behind common interface", "Convert interface", "Notify observers"],
        1,
        "Strategy defines family of algorithms delegating behavior at runtime."),
    mcq("software-development", "Testing", "medium", "theory",
        "Test pyramid suggests:",
        ["Most tests are slow UI E2E", "Many fast unit tests, fewer integration, fewest E2E", "Only manual tests", "No unit tests"],
        1,
        "Pyramid favors cheap unit tests at base, minimal brittle E2E at top."),
    mcq("software-development", "Event-Driven", "hard", "theory",
        "Eventual consistency in event-sourced systems means:",
        ["No consistency ever", "Readers may lag until projections catch up", "Synchronous 2PC required", "No events stored"],
        1,
        "Projections/read models update asynchronously after events append."),
    mcq("software-development", "DDD", "hard", "theory",
        "Aggregate root responsibility:",
        ["Map every table 1:1", "Enforce invariants for cluster of entities; external refs by id only", "Handle HTTP only", "Replace repositories"],
        1,
        "Aggregate boundary is consistency boundary; outside references use identity."),
    mcq("software-development", "CI/CD", "hard", "practical",
        "Blue-green deployment reduces downtime by:",
        ["Deleting old version first", "Switching traffic from idle (green) environment after validation", "Only feature flags", "Manual FTP"],
        1,
        "Two environments; cutover router/load balancer after green is healthy."),
    mcq("software-development", "Threat Modeling", "hard", "theory",
        "STRIDE spoofing threat mitigated often by:",
        ["Ignoring auth", "Strong authentication and token validation", "More logging only", "Bigger servers"],
        1,
        "Spoofing identity — mitigate with authn, MFA, signed tokens."),
    mcq("software-development", "Contracts", "hard", "theory",
        "Consumer-driven contract tests verify:",
        ["Database schema only", "Provider meets expectations defined by consumer interactions", "UI colors", "Git hooks"],
        1,
        "Pact-style contracts ensure API compatibility with consumer-defined examples."),
    mcq("software-development", "Latency", "hard", "theory",
        "Little's Law L = λW relates:",
        ["CPU to RAM", "Average items in system = arrival rate × average time in system", "Threads to cores only", "Disk to network"],
        1,
        "Queueing theory: concurrency, throughput, and residence time."),
    mcq("software-development", "Feature Flags", "hard", "practical",
        "Kill switch for bad release should:",
        ["Require redeploy", "Disable feature via flag/config without full rollback when possible", "Drop database", "Clear logs"],
        1,
        "Runtime flags can disable paths quickly while investigating."),
    mcq("software-development", "Anti-patterns", "hard", "theory",
        "Distributed monolith anti-pattern means:",
        ["Too many small services", "Tightly coupled services requiring coordinated deploys — defeats independence", "Single JVM", "Using REST"],
        1,
        "Services share DB/chatty sync calls and deploy together — microservices cost without benefits."),
]


def validate(questions, test_id, expected_medium, expected_hard):
    assert len(questions) == 60, f"{test_id}: expected 60 questions, got {len(questions)}"
    cats = ["core-java", "dbms", "backend", "docker", "angular", "software-development"]
    for c in cats:
        n = sum(1 for q in questions if q["category"] == c)
        assert n == 10, f"{test_id}: category {c} has {n} questions"
    easy = sum(1 for q in questions if q["difficulty"] == "easy")
    med = sum(1 for q in questions if q["difficulty"] == "medium")
    hard = sum(1 for q in questions if q["difficulty"] == "hard")
    assert easy == 0, f"{test_id}: found {easy} easy"
    assert med == expected_medium, f"{test_id}: medium {med} != {expected_medium}"
    assert hard == expected_hard, f"{test_id}: hard {hard} != {expected_hard}"
    for i, q in enumerate(questions):
        assert len(q["options"]) == 4, f"{test_id} Q{i+1}: need 4 options"
        assert 0 <= q["answer"] <= 3, f"{test_id} Q{i+1}: invalid answer index"


def write_test(path, meta, questions):
    validate(questions, meta["id"], meta["_expected_medium"], meta["_expected_hard"])
    out = {k: v for k, v in meta.items() if not k.startswith("_")}
    out["questions"] = questions
    path.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {path} ({len(questions)} questions)")


def main():
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    write_test(
        DATA_DIR / "test-02.json",
        {
            "id": "test-02",
            "title": "Comprehensive Test 2 — Intermediate to Advanced",
            "toughness": "Intermediate to Advanced — Medium & Hard only",
            "durationMinutes": 60,
            "_expected_medium": 28,
            "_expected_hard": 32,
        },
        TEST_02_QUESTIONS,
    )
    write_test(
        DATA_DIR / "test-03.json",
        {
            "id": "test-03",
            "title": "Comprehensive Test 3 — Advanced / Challenge",
            "toughness": "Advanced / Challenge — Medium & Hard (Hard focus)",
            "durationMinutes": 60,
            "_expected_medium": 12,
            "_expected_hard": 48,
        },
        TEST_03_QUESTIONS,
    )


if __name__ == "__main__":
    main()
